Delete unused files

diff --git a/Library/zsh/functions/error b/Library/zsh/functions/error
--- a/Library/zsh/functions/error
+++ b/Library/zsh/functions/error
@@ -22,7 +22,6 @@ function error() {
   # Name of the caller
   typeset default_title='Error'
   typeset prog
-#=${(C)0}
   
   # Error message
   typeset message
@@ -39,22 +38,20 @@ function error() {
   typeset -i autouppercase=0
   typeset -i autolowercase=0
   typeset -i remove_trailing_space=1
-  typeset -i trailing_period=1
-  typeset -i highlight_variables=1
-  typeset -i return_on_exit=1
-  typeset -i print_description=1
-  typeset -i print_funcstat=0
-  typeset -i always_default=0
+  typeset -i trailing_period=0
+  typeset -i highlight_variables=1 # -H
+  typeset -i return_on_exit=1      # +R
+  typeset -i print_description=1   # +D
+  typeset -i print_functrace=0     # -F
+  typeset -i always_default=0      # -T
+  typeset -i print_process_error=1 # +p
   
   
   
   
-  #MARK: - Functions
   # Highlight all shell '$variables' in description
   autoload -Uz syntaxf
   function error-replace-variables() syntaxf -c 1 $argv
-  
-  
   
   
   #MARK: Format
@@ -107,16 +104,18 @@ function error() {
   # Format and print the error/warning message
   function error-format() {
     if [[ $always_default -eq 1 ]]; then
-      prog=${default_title}
+      prog="$default_title"
     fi
     error-format-title
     error-format-description
     
     local prefix="${message_title}${exit_code_label}"
-    if [[ -n $message_desc ]]; then
-      print "${prefix}: ${message_desc}"
+    local tab_width="-x $(( ${#$(rmcolor $prefix)} + 2 ))"
+    
+    if [[ -n "$message_desc" ]]; then
+      print -l $tab_width -- "${prefix}: ${message_desc}"
     else
-      print "${prefix}."
+      print -- "${prefix}."
     fi
     return 0
   }
@@ -124,18 +123,27 @@ function error() {
   
   
   
+  
+  
+  
   #MARK: - Command Arguments
-  # Treat the very first flag as error code:
-  #   'error -123' == 'error -e 123'
+  # Treat the first flag as exit code if it is
+  # numeric: 'error -123' == 'error -e 123'.
   if [[ $1 =~ ^[-][0-9]+$ ]]; then
     set -- '-e' ${1#-} ${argv:2}
   fi
   
-  # Parse other `error' options
-  
+  # Parse other function options
   while [[ $1 =~ ^[-+] ]] &&
         [[ $1 != '--' ]]; do
     case $1 in
+      # Print short error message and exit
+      (-)
+        print -- "$default_title($exit_code) $argv" >&2
+        return $exit_code
+      ;;
+      
+      
       ## error -h,--help: show help message ##
       (-h|--help)
         fn print-commands $0
@@ -148,7 +156,7 @@ function error() {
           exit_code=$val
           shift
         else
-          ( error -1 'Exit code $val is invalid' )
+          (v="$val" error -1 'Exit code ${v} is invalid')
           return $?
         fi
       ;;
@@ -169,7 +177,11 @@ function error() {
         shift
       ;;
       
+      ([-+]p)
+        let print_process_error=$(boolopt $1 0 1)
+      ;;
       
+
       
       
       # Additional formatting options
@@ -208,7 +220,7 @@ function error() {
       ## error -F,--funcstat: display 'funcstat' ##
       ## error +F,--no-funcstat: do not display 'funcstat' ##
       ([-+]F|--(no-|)funcstat)
-        let print_funcstat=$(boolopt $1 1 0)
+        let print_functrace=$(boolopt $1 1 0)
       ;;
       ## error -D,--description: print error description ##
       ## error +D,--no-description: do not print error description ##
@@ -219,6 +231,7 @@ function error() {
         fi
       ;;
       
+      
       # Stop parsing options
       *)  break ;;
     esac
@@ -227,31 +240,45 @@ function error() {
   [[ $1 == '--' ]] && shift
   
   
+  
+  
+  
+  
+  
+  if zselect -t 0 -r 0; then
+    set -- ${(@f)"$(<&0)"} $argv
+  fi
+  message_desc=${argv}
+  
+  
   # If program display name is not set, set it to
   #    name of the command which called 'error'.
   # If 'error' is called directly from the shell,
   #    then set program name to default title.
-  if [[ -z $prog ]]; then
+  if [[ -z "$prog" ]]; then
     prog=${funcstack[2]:-$default_title}
   fi
   
   # If -L is set, set description to remaining arguments
   if [[ $split_lines -eq 1 ]]; then
-    message_desc=${(@F)argv}
-  else
-    message_desc=${argv}
+    local -a text_lines
+    set   -A text_lines   "$1" $'\n\t'${(@Ff)^argv:2}
+    message_desc=${text_lines}
   fi
   
-  # If -D is set, format and print error description
-  if [[ $print_description -eq 1 ]]; then
+  # If +D is not set, format and print error description.
+  # If -p is set, do not print subprocess errors
+  # (e.g., `result=$(error)').
+  if [[ $print_description -eq 1 ]] &&
+     [[ -t 2 || $print_process_error -eq 1 ]]; then
     message_desc=$(syntaxf $message_desc)
     message=$(error-format)
-    print -u2 -P -- "${message}"
+    print -P -- "${message}" >&2
   fi
   
   # If -F is set, print function stack
-  if [[ $print_funcstat -eq 1 ]]; then
-    funcstat
+  if [[ $print_functrace -eq 1 ]]; then
+    print -P -- "%F{$c_error}Trace%f: ${(@j:, :)functrace}." >&2
   fi
   
   # If +R is not set, execute a return statement
@@ -263,7 +290,6 @@ function error() {
   fi
   
   # Unset error subfunctions
-  unset -f -m 'error_*'
+  unset -f -m 'error-*'
   return $exit_code
 }
-
