[CS850-0511] 1 file changed, 3 insertions(+), 1 deletion(-).
Signed-off-by: Maxim Puchkov <maxim_puchkov@sfu.ca>

diff --git a/Services/Committer b/Services/Committer
--- a/Services/Committer
+++ b/Services/Committer
@@ -14,6 +14,7 @@ echo "${log_prefix} Service started."
 typeset -a opts
 opts=()
 if [[ $1 == '-d' ]]; then
+  echo "${log_prefix} Dry-run enabled"
   opts+='--dry-run'
   shift
 fi
@@ -21,7 +22,7 @@ fi
 # Commit ID
 typeset id_file=etc/commit.id
 if [[ ! -r $id_file ]]; then
-  echo "${log_prefix} ID file missing." >&2
+  echo "${log_prefix} ID file missing ${id_file}." >&2
   exit 1
 fi
 typeset -i -Z3 commit_id
@@ -59,4 +60,5 @@ echo $(( $commit_id + 1 )) > $id_file
 #echo "${log_prefix} [0] OK."
 
 echo "${log_prefix} Service exited."
+echo
 exit 0
