[CS934-0610] 48 files changed, 1248 insertions(+), 603 deletions(-).
Signed-off-by: Maxim Puchkov <maxim_puchkov@sfu.ca>

diff --git a/Services/Identity b/Services/Identity
--- a/Services/Identity
+++ b/Services/Identity
@@ -7,23 +7,102 @@
 #  Copyright © 2020 Maxim Puchkov. All rights reserved.
 
 
-# Data
-#typeset identity_ssh_file
-#identity_ssh_file='etc/identity.ssh'
-#
-#typeset default_status current_status
-#default_status=0
-#current_status=$(< $identity_ssh_file)
-#
-#typeset log_prefix
-#log_prefix="$(date -j +'%b %d %T') $(hostname -s) ${0:t}[$$]:\t"
+#function log() {
+#    typeset
+#    typeset log_prefix="$(date -j +'%b %d %T') $(hostname -s) ${0:t}[${$}]:\t"
+#}
+
+fpath=(/usr/local/Terminal/zsh/functions $fpath)
+autoload -Uz logm
+logm "Hello, logs"
+logm "I'm here!"
+
+exit 12345
 
 
+typeset log_prefix="$(date -j +'%b %d %T') $(hostname -s) ${0:t}[${$}]:\t"
+echo "${log_prefix} Service started."
+
+# Key file
+typeset key=~/.ssh/id_rsa
+if ! ssh-add -T -- $key &>/dev/null; then
+    echo "${log_prefix} Adding private key ${key}."
+    ssh-add -- $key
+fi
+
+# Check status
+typeset -i return_code=$?
+if [[ $return_code -eq 0 ]]; then
+    echo "${log_prefix} Private key ${key} added successfully."
+else
+    echo "${log_prefix} [${return_code}] Failed to add key ${key}." >&2
+fi
+
+
+echo "${log_prefix} Service stopped."
+return $return_code
+
+#fgrep -f <(ssh-keygen -lf ~/.ssh/id_rsa) <(ssh-add -l)
+#if [[ $? -ne 0 ]]; then
+#    ssh-add
+#fi
+#
+
+return 0;
+
+
+#typeset fingerprint=$(ssh-keygen -l -f $public_key)
+alias p='() { print -P "%S${argv}%s"; }'
+
+# () { print-var argv; grep -f $1 $2; C } =(ssh-keygen -lf $pk) =(ssh-add -l)
+
+
+#() {
+#    fgrep -f $1 < $2
+#} <(ssh-keygen -lf $public_key) \
+#  <(ssh-add -l)
+
+
+() {
+    print-var argv
+    if fgrep -f $1 < $2; then
+        p 'grep returns true'
+#        p "{$(<$1)}"
+    fi
+    return $?
+} <(ssh-keygen -lf $public_key) =(ssh-add -l)
+
+
+return 0
+
+
+#ssh-keygen -lf $public_key
+if [[ $fingerprint =~ "$(ssh-add -l)" ]]; then
+    echo 'OK O KO K  OS OS O S OSO SO O'
+fi
+ssh-add -l
+
+
+return 0
+
+case $(() {
+    ssh-add -l | fgrep -f $1
+} =(ssh-keygen -l -f $public_key)) in
+#
+0) p '%S~~ 0'
+;;
+1) p '~~ 1'
+;;
+*) p
+
+;;
+esac
+
+return $?
 # Data
-typeset identity_ssh_file='etc/identity.ssh'
-typeset default_status=0
-typeset current_status=$(< $identity_ssh_file)
-typeset log_prefix="$(date -j +'%b %d %T') $(hostname -s) ${0:t}[$$]:\t"
+#typeset identity_ssh_file='etc/identity.ssh'
+#typeset default_status=0
+#typeset current_status=$(<$identity_ssh_file)
 
 
 # Cancel if 
@@ -37,3 +116,4 @@ fi
 echo $default_status > $identity_ssh_file
 echo "${log_prefix} [0] Status changed from $current_status to $default_status."
 exit 0
+
diff --git a/Services/update-service b/Services/update-service
--- a/Services/update-service
+++ b/Services/update-service
@@ -11,29 +11,45 @@ log_prefix="$(date -j +'%b %d %T') $(hostname -s) ${0:t}[$$]:\t"
 echo "${log_prefix} Service started."
 
 
+function test_command() {
+    command_name="$1"
+    if ! whence ${(P)command_name} &>/dev/null; then
+        echo "${log_prefix} [127] Command not found: ${command_name:l}." >&2
+        exit 127
+    fi
+    return 0
+}
+
+
+# Input
+BREW=$1
+test_command BREW
+TLDR=$2
+test_command TLDR
+
 # Before update
-brew_before=${#$( brew outdated --quiet )}
-tldr_before=${#$( tldr --list )}
+brew_before=${#$( $BREW outdated --quiet )}
+tldr_before=${#$( $TLDR --list )}
 error=0
 
 
 #MARK: - Update
 ( # Update Homebrew formulae
   echo "Updating Homebrew..."
-  brew update
+  $BREW update
   echo "Upgrading Homebrew formulae..."
-  brew upgrade
+  $BREW upgrade
 ) && (
   # Update tldr
-  Info "Updating TLDR..."
-  tldr --update
+  echo "Updating TLDR..."
+  $TLDR --update
 ) || error=$?
 
 
 if [[ $error -eq 0 ]]; then
   # After update
-  brew_after=${#$( brew outdated --quiet )}
-  tldr_after=${#$( tldr --list )}
+  brew_after=${#$( $BREW outdated --quiet )}
+  tldr_after=${#$( $TLDR --list )}
   # Difference
   brew_diff=$(( $brew_before - $brew_after ))
   tldr_diff=$(( $tldr_after - $tldr_before ))
diff --git a/zsh/functions/fn b/zsh/functions/fn
--- a/zsh/functions/fn
+++ b/zsh/functions/fn
@@ -8,39 +8,61 @@
 
 
 # Information about shell functions.
+
+# Options:
+## -h,--help: show help ##
 function fn() (
     ## def: print function definition ##
     function fn_def() {
-        local fdef=$( functions $fname )
-        local highlight=(pygmentize -f 'terminal16m' -O style='xcodedark' -l 'zsh')
-        if [[ -z ${commands[pygmentize]} ]]; then
-            error -0 'Cannot find pygments.'
-            highlight='cat'
-        fi
-        printf '%s\n' "$fdef" | $highlight
+        print -P -N -- "%Ufunction%u "
+        functions $fn_name | highlight
+        return $?
     }
     ## src: find function source file ##
     function fn_src() {
-        local fsource=$functions_source[$fname]
+        local fsource=$functions_source[$fn_name]
         if [[ -z $fsource ]]; then
-            error "Definition file not found: %F{1}${fname}%f."
+            error -1 'Function definition file for $fn_name was not found.'
             return 1
         fi
-        echo "$fsource"
+        # Abbreviate directories
+        local -a output_flags=('-P')
+        if [[ -t 1 ]]; then
+            output_flags+=('-D')
+        fi
+        builtin print $=output_flags -- $fsource
         return 0
     }
+    ## show: display function definition and source file ##
+    function fn_show() {
+        local code=$(fn def $fn_name)
+        local file=$(fn src $fn_name)
+        printf '%s\n\n' "$code"
+        print -Pf '%s\n' "%U${(D)file}%u"
+        return 0
+    }
+    ## open: open function source file ##
+    function fn_open() {
+        local file=$(fn src $fn_name 2>/dev/null)
+        if [[ ! -r $file ]]; then
+            error -1 'Cannot read source file for function $fn_name.'
+        fi
+        open -a Xcode $file
+        return 0
+    }
+    
     ## isdef: check if a function is defined ##
     function fn_isdef() {
-        if [[ ${+functions[$fname]} -ne 1 ]]; then
+        if [[ ${+functions[$fn_name]} -ne 1 ]]; then
             return 1
         fi
         return 0
     }
     ## sub: list functions defined within a function ##
     function fn_sub() {
-        name_prefix="${name_prefix:-${fname%%_*}}"
+        name_prefix="${name_prefix:-${fn_name%%_*}}"
         typeset srcfile
-        if ! srcfile=$( fn src $fname ); then
+        if ! srcfile=$( fn src $fn_name ); then
             return 1
         fi
         typeset -a list
@@ -50,53 +72,192 @@ function fn() (
                        $srcfile ))
         typeset f
         for f in $list; do
-            typeset subfname=${f%'('*')'}
-            if [[ ${+functions[$subfname]} ]]; then
-                printf '%s\n' "$subfname"
+            typeset subfn_name=${f%'('*')'}
+            if [[ ${+functions[$subfn_name]} ]]; then
+                printf '%s\n' "$subfn_name"
             fi
         done
         return 0
     }
     ## commands: list function commands ##
     function fn_commands() {
-        name_prefix="${name_prefix:-${fname%%_*}}"
-        typeset -a fcommands=(${$( fn -p $name_prefix sub $fname )//${name_prefix}_/})
+        name_prefix="${name_prefix:-${fn_name%%_*}}"
+        typeset -a fcommands=(${$( fn -p $name_prefix sub $fn_name )//${name_prefix}_/})
         printf '%s\n' $fcommands
         return 0
     }
     ## print-commands: format and list function commands ## [Function]
     function fn_print-commands() {
-        name_prefix="${name_prefix:-${fname%%_*}}"
-        print_h1 "%U${fname}%u commands:"
-        print -P -l "%F{14}$( fn -p $name_prefix commands $fname )%f"
+        name_prefix="${name_prefix:-${fn_name%%_*}}"
+        print_h1 "%U${fn_name}%u commands:"
+        print -P -l -- "%F{14}$( fn -p $name_prefix commands $fn_name )%f"
         return 0
     }
+    ## options: list function flags and options ##
+    function fn_options() {
+        typeset grep_pattern='^[ ]*##[ ]*-[^ ]+: .* ##[ ]*$'
+        typeset sed_pattern='s/## ([-].*): (.*) ##/\1: \2/p'
+        typeset -A reply
+        reply=("${(@f)$(grep -E $grep_pattern $srcfile |
+            sed -n -E $sed_pattern |
+            awk -F ': ' '{print $1; print $2;}' )}")
+        # Print completion for arguments
+        local k v
+        for k v in ${(kv)reply}; do
+            if [[ $k =~ '[,]' ]]; then
+                k="{$k}"
+            fi
+            printf '\t%s"[%s]" \\\\\n' "$k" "$v"
+        done
+    }
+#    function fn_options() {
+#        name_prefix="${name_prefix:-${fn_name%%_*}}"
+#        typeset srcfile
+#        if ! srcfile=$( fn src $fn_name ); then
+#            return 1
+#        fi
+##        typeset -a list
+##        list=($( egrep --only-matching \
+##                       --ignore-case \
+##                       --regexp "^[ ]*## -[^ ,]+(,[^ ,]+)? ##" -- \
+##                       $srcfile ))
+##        typeset -A reply
+#        typeset grep_pattern='^[ ]*##[ ]*-[^ ]+: .* ##[ ]*$'
+#        typeset sed_pattern='s/## ([-].*): (.*) ##/\1 "\2"/p'
+#        typeset -a reply
+#        reply=("${(@f)$(grep -E $grep_pattern $srcfile |
+#            sed -n -E $sed_pattern)}")
+##        grep -E $grep_pattern $zfunc/fn |
+##            sed -n -E $sed_pattern
+#
+##        print-var list
+##        awk -F '## | ##|: ' '/## -.*: .* ##/ { print "2={"$2"}"; }' $srcfile
+##        typeset f
+##        for f in $list; do
+##            typeset subfn_name=${f%'('*')'}
+##            if [[ ${+functions[$subfn_name]} ]]; then
+##                printf '%s\n' "$subfn_name"
+##            fi
+##        done
+#        return 0
+#    }
+#
     
+    
+    
+    # Completion for commands
+    function fn_commands_completion() {
+        if
+        typeset -A reply
+        typeset file=$1
+        typeset -a fn_commands=($(fn -p ${file:t} commands ${file:t}))
+        # Parse commands
+        for cmd in $fn_commands; do
+            local pattern="## ${cmd}: .+ ##.*function ${fn_name}[\-\_]${cmd}[\s]*\(\)"
+            local description=$(
+                greps '-o' "$pattern" "$file" |
+                    head -n 1 |
+                    sed -e "s/## ${cmd}: //g" -e "s/ ##.*//g"
+            )
+            reply[$cmd]="${description:-''}"
+        done
+        # Print command completion
+        for k v in ${(kv)reply}; do
+            printf '\t%s:"%s"\n' "$k" "$v" | colrm
+        done
+    }
+    
+    
+    
+    
+    #MARK: - Z-Shell Function Completion
     ## completion: generate function command completion ##
     function fn_completion() {
-        # Find files starting with the specified 'fn_name'
-        typeset -A reply
-        typeset -a fn_files=()
-        typeset -a fn_commands=()
-        # Parse each file and generate associative array 'reply[command]=description'
-        typeset fn_dir f cmd
-        fn_dir="${$(fn src $fname):h}"
-        for f in ${fn_dir}/${fname}*; do
-            autoload +X ${f:t}
-            fn_commands=($( fn -p ${f:t} commands ${f:t} ))
+        # Completion for flags and options
+        function completion_arguments() {
+            typeset grep_pattern='^[ ]*##[ ]*-[^ ]+: .* ##[ ]*$'
+            typeset sed_pattern='s/## ([-].*): (.*) ##/\1: \2/p'
+            typeset -A reply
+            reply=("${(@f)$(grep -E $grep_pattern $zfunc/fn |
+                sed -n -E $sed_pattern |
+                awk -F ': ' '{print $1; print $2;}' )}")
+            # Print completion for arguments
+            local k v
+            for k v in ${(kv)reply}; do
+                if [[ $k =~ '[,]' ]]; then
+                    k="{$k}"
+                fi
+                printf '\t%s"[%s]" \\\\\n' "$k" "$v"
+            done
+        }
+        # Completion for commands
+        function completion_commands() {
+            typeset -A reply
+            typeset file=$1
+            typeset -a fn_commands=($(fn -p ${file:t} commands ${file:t}))
+            # Parse commands
             for cmd in $fn_commands; do
-                local pattern="## ${cmd}: .+ ##.*function ${fname}[\-\_]${cmd}[\s]*\(\)"
+                local pattern="## ${cmd}: .+ ##.*function ${fn_name}[\-\_]${cmd}[\s]*\(\)"
                 local description=$(
-                    greps '-o' "$pattern" "$f" |
+                    greps '-o' "$pattern" "$file" |
                         head -n 1 |
                         sed -e "s/## ${cmd}: //g" -e "s/ ##.*//g"
                 )
                 reply[$cmd]="${description:-''}"
             done
+            # Print command completion
+            for k v in ${(kv)reply}; do
+                printf '\t%s:"%s"\n' "$k" "$v" | colrm
+            done
+        }
+        # Find files starting with the specified 'fn_name'
+        typeset -a cmd_completion=()
+        typeset -a arg_completion=()
+        # Parse each file and generate argument/command completion
+        typeset fn_dir file cmd
+        fn_dir="${$( fn src $fn_name ):h}"
+        for file in ${fn_dir}/${fn_name}*; do
+            autoload +X ${file:t}
+            arg_completion=(${(@f)"$(completion_arguments $file)"})
+            cmd_completion=(${(@f)"$(completion_commands $file)"})
         done
-        for k v in ${(kv)reply}; do
-            printf '  %s:"%s"\n' "$k" "$v" | colrm
-        done
+        
+cat <<EOF
+#compdef ${fn_name}
+
+# _${fn_name}
+# ${(D)fn_dir}/${fn_name}
+#
+# zsh function completion
+# $(date -j +'Updated on %F at %I:%M %p')
+
+
+_arguments -C \\
+$( print -x2 -l -- ${arg_completion} )
+  ":command:->command" \\
+  "*::arg:->arg"
+
+case \$state in
+  (command)
+    typeset -a commands
+    commands=(
+$( print -x6 -l -- ${cmd_completion} )
+    )
+    _describe -t commands command commands
+  ;;
+  (arg)
+    typeset -a args
+    args=(
+      # Completion for commands' arguments
+    )
+    _describe -t args arg args
+  ;;
+esac
+
+return 0
+EOF
+        
+        return 0
     }
     
     # Options
@@ -124,25 +285,29 @@ function fn() (
     # fn command argument
     typeset cmd=$1
     shift
-    if ! ( functions | grep -w -e "fn[-_]$cmd" &>/dev/null ); then
+    if ! ( functions + | grep -w -e "fn[-_]$cmd" &>/dev/null ); then
         error "Unknown command: %F{1}$cmd%f."
         return 127
     fi
     
-    typeset fname="$@"
+    typeset fn_name="$@"
     if [[ $cmd == 'isdef' ]]; then
-        ${0}_${cmd} $fname
+        ${0}_${cmd} $fn_name
         return $?
     fi
     
     # Return if function is not defined
-    if [[ ${+functions[$fname]} -eq 0 ]]; then
-        error "Function %F{1}$fname%f is not defined."
+    if [[ ${+functions[$fn_name]} -eq 0 ]]; then
+        error "Function %F{1}$fn_name%f is not defined."
         return 1
     fi
     
     # Execute the command
-    autoload +X $fname
-    ${0}_${cmd} $fname
-    return $?
+    autoload +X $fn_name
+    ${0}_${cmd} $fn_name
+    if [[ $? -ne 0 ]]; then
+        local cmd_text="$0 $cmd $fn_name"
+        error -1 'Command error: $cmd_text.'
+    fi
+    return 0
 )
diff --git a/zsh/functions/highlight b/zsh/functions/highlight
--- a/zsh/functions/highlight
+++ b/zsh/functions/highlight
@@ -9,41 +9,64 @@
 
 # Highlight code syntax
 function highlight() {
-    trap "unfunction -m '${0}-*'" EXIT
+#    # Syntax highlighting
+#    function highlight-syntax() {
+#        ${=cmd} -f 'terminal16m' \
+#                -O style='xcodedark' \
+#                -l 'zsh' \
+#                "$@"
+#        return $?
+#    }
     
-    # Syntax highlighting
     function highlight-syntax() {
-        ${=cmd} -f 'terminal16m' \
-                -O style='xcodedark' \
-                -l 'zsh' \
-                "$@"
+        $=cmd $=flags "$@"
         return $?
     }
     
+    # Flags
+    typeset -a flags=()
+    if [[ $# -le 1 ]]; then
+        flags=(-f 'terminal16m' -O style='xcodedark' -l 'zsh')
+    else
+        flags=(${argv:1:-1})
+    fi
     
-    #
-    typeset cmd='pygmentize'
-    typeset input_file=${${@:a}:-/dev/stdin}
+    # Input file
+    typeset filename=${${@[-1]:a}:-/dev/stdin}
+
+    
+    
+    # Highlight command
+    typeset cmd_name cmd
+    cmd_name='pygmentize'
+    cmd=${commands[$cmd_name]}
+    if [[ -z $cmd ]]; then
+        error -127 'Command not found: $cmd_name.'
+        return 0
+    fi
+    
+
+    
+    
     
     
     # Check input
     if [[ $# -eq 0 ]] && [[ ! -p /dev/stdin ]]; then
         error -2 'No input.'
     fi
-    # Check 'pygmentize' command
-    if [[ -z ${commands[$cmd]} ]]; then
-        error -1 "Command not found: %F{1}${cmd}%f."
+    # Check input file exists
+    if [[ ! -e $filename ]]; then
+        error -1 "File not found: %F{1}${filename}%f."
     fi
-    # Check input file
-    if [[ ! -e $input_file ]]; then
-        error -1 "File not found: %F{1}${input_file}%f."
-    fi
-    if [[ ! -r $input_file ]]; then
-        error -1 "Cannot read from %F{1}${input_file}%f."
+    # Check input file is readable
+    if [[ ! -r $filename ]]; then
+        error -1 "Cannot read from %F{1}${filename}%f."
     fi
     
     
     #
-    highlight-syntax $input_file
-    return $?
+    highlight-syntax $filename
+    
+    unfunction -m '${0}-*'
+    return 0
 }
diff --git a/zsh/functions/template b/zsh/functions/template
--- a/zsh/functions/template
+++ b/zsh/functions/template
@@ -67,7 +67,7 @@ function template() {
         fi
         
         # Copy the original template file to new location
-        if ! ( cp -n $template_orig $template_new ); then
+        if ! ( command cp -n $template_orig $template_new ); then
             error 'Fatal error.'
             return 1
         fi
@@ -82,7 +82,8 @@ function template() {
     }
     
     
-    #MARK: - Z-Shell Command Template
+    #MARK: - Z-Shell command template
+    ## zsh: zsh script ##
     function template_zsh() {
         target_dir="${target_dir:-${PWD}}"
         name="${$( generate_filename ${1:-${(U)0}} )}"
@@ -94,7 +95,8 @@ function template() {
         copy_template
     }
     
-    #MARK: - Z-Shell Function
+    #MARK: - Z-Shell function
+    ## zfunction: zsh autoload function
     function template_zfunction() {
         target_dir="${target_dir:-${zfunc}}"
         name="${$( generate_filename $1 ):-${(U)0}}"
@@ -117,7 +119,8 @@ function template() {
 #        copy_template
 #    }
     
-    #MARK: - Python Script
+    #MARK: - Python script
+    ## python: python3 script ##
     function template_python() {
         target_dir="${target_dir:-${PWD}}"
         name="${$( generate_filename ${1:-${(U)0}} )}"
@@ -131,7 +134,8 @@ function template() {
         fi
     }
     
-    #MARK: - Z-Shell Completion
+    #MARK: - Z-Shell completion function
+    ## zcompletion: zsh function completion ##
     function template_zcompletion() {
         target_dir="${target_dir:-${ZDOTDIR}/completions}"
         name="${$( generate_filename _${1:-${(U)0}} )}"
@@ -142,10 +146,11 @@ function template() {
         
         zfc completion "$1" > "$template_orig"
         copy_template
-        rm -f "$template_orig"
+        command rm -f "$template_orig"
     }
     
-    #MARK: - Z-Shell Tools
+    #MARK: - Z-Shell tool
+    ## ztool: standalone zsh script ##
     function template_ztool() {
         target_dir="${target_dir:-${ZTERM}/Tools}"
         name="${$( generate_filename ${1:-${(U)0}} )}"
@@ -158,10 +163,10 @@ function template() {
         fi
     }
     
-    #MARK: - launchd service
+    #MARK: - Launchd service
     function template_launchd() {
         target_dir="${target_dir:-${ZTERM}/etc/$1}"
-        mkdir $target_dir
+        command mkdir -p -- $target_dir
         name="${$( generate_filename ${m_organization_id}.services.${1:-${(U)0}} )}.plist"
         m_filename=$name
         m_package_name='Services'
@@ -170,8 +175,30 @@ function template() {
         copy_template
         
         template -d $ZTERM/Services ztool $1
-        ln -s  $ZTERM/etc/$1/$name  $HOME/Library/LaunchAgents/$name
-        ln -s  $ZTERM/Services/$1   /usr/local/bin/$1
+        command ln -s -- $target_dir/$name  $HOME/Library/LaunchAgents/$name
+        command ln -s -- $ZTERM/Services/$1 /usr/local/bin/$1
+    }
+    
+    #MARK: - Oh-my-zsh custom plugin
+    function template_plugin() {
+        target_dir="${target_dir:-${ZDOTDIR/plugins/$1}}"
+        mkdir -p -- $target_dir
+        name="${$( generate_filename $1 ):-${(U)0}}.plugin.zsh"
+        m_filename=$name
+        m_package_name='Oh-my-zsh plugin'
+        template_new="${target_dir}/${name}"
+        template_orig="$templates_dir/$0"
+        copy_template
+        
+        command mkdir -p -- $target_dir
+        command ln -s -- $target_dir/$name $ZDOTDIR/.oh-my-zsh/plugins/custom/$1/$name
+        
+    }
+    
+    
+    function template_null() {
+        print -P "Called $0"
+        print-fstack
     }
     
     
@@ -227,12 +254,14 @@ function template() {
     
     # Subcommand
     typeset cmd=$1
-    shift
     if ! (whence ${0}_${cmd} &>/dev/null); then
-        error "Function command not found: %F{1}$cmd%f."
-        return 127
+        error -127 'Function command not found: $cmd.'
     fi
-    
+    shift
     ${0}_${cmd} "$@"
-    return $?
+    typeset -i exit_code=$?
+    
+#    builtin print -P -- "${0}: done."
+    logm "Done"
+    return $exit_code
 }
