AutoCompletion generators

diff --git a/zsh/functions/zshell/fn b/zsh/functions/zshell/fn
--- a/zsh/functions/zshell/fn
+++ b/zsh/functions/zshell/fn
@@ -1,148 +1,118 @@
 #!/bin/zsh
 
 #  fn
-#  Dev X
+#  Z-Function
 #
 #  Created by mpuchkov on 2020-03-12.
 #  Copyright © 2020 Maxim Puchkov. All rights reserved.
 
 
-# Function fn.
-function fn() {
+# Information about shell functions.
+function fn() (
     
-    #MARK: - Function Body
-#    function fn_body() {
-#        # Check syntax.
-#        SYNTAX=(fn body function_name...)
-#        if [[ -z $1 ]]; then
-#            serror 'function_name' "$SYNTAX"; return 1
-#        fi
-#
-#
-#        # Highlight function name, brackets, shell keywords, etc.
-#        function function_highlight() {
-#            # Highlight declaration.
-#            h_fname=$(underline $(bold $(b_bmagenta $fname)))
-#            local h_fdef="function ${h_fname}() {$fbody}"
-#
-#            # Highlight syntax elements.
-#            local h_brackets=( '{' '}' "'" )
-#              highlight_format[magenta]=$h_brackets
-#            local h_quotes=( "\'" "\"" )
-#              highlight_format[b_yellow]=$h_quotes
-#            local h_reswords=( $reswords ']]' )
-#              EXCLUDE=( $h_brackets )
-#              highlight_format[b_magenta]=${h_reswords:|EXCLUDE}
-#            local h_builtins=( ${(k)builtins} '$' '%' '@' )
-#              EXCLUDE=( '[' 'r' '.' )
-#              highlight_format[green]=${h_builtins:|EXCLUDE}
-#
-#            # For every color, highlight every element.
-#            for color in ${(k)highlight_format}; do
-#                for element in ${(z)highlight_format[$color]}; do
-#                    local highlight_element=$( $color $element )
-#                    h_fdef=${h_fdef//$element/$highlight_element}
-#                done
-#            done
-#            echo $h_fdef
-#        }
-#
-#
-#       # Function contents.
-#        local fname fdef fdecl fbody
-#        local fprefix fsuffix
-#
-#        # Syntax highlight.
-#        typeset -A highlight_format
-#        local h_fname
-#
-#        # For each name in input, check if a function with
-#        # the same name is defined.
-#        for fname in "$@"; do
-#            fdef=$( functions $fname )
-#            fdecl="$fname ()"
-#            # Prefix and Suffix delimiters.
-#            fprefix="$fdecl {"
-#            fsuffix="}"
-#
-#            # Print highlighted function syntax and its source file.
-#            if [[ -n $fdef ]]; then
-#                fbody=${${fdef#$fprefix}%$fsuffix}
-#                fsourcefile=$(fn src $fname)
-#                # Highlighted.
-#                h_fname="$(underline $(b_bmagenta $fname))"
-#                h_fdecl="function ${h_fname}() { $fbody \n}"
-#                h_fdef=$( function_highlight $fdef $fname )
-#                echo $h_fdef
-#                echo; echo;
-#                echo "> $h_fname is a function defined in"
-#                echo "    $fsourcefile"
-#            else
-#                # Otherwise, print error.
-#                echo "$(Bad $fname) is not a function."
-#            fi
-#        done
-#    }
-    
-    function fn_body() {
-        for fname in "$@"; do
-            fdef=$( functions $fname )
-            printf '%s\n' "$fdef" | pygmentize -l zsh
-        done
+    ## def: print function definition ##
+    function fn_def() {
+        local fdef=$( functions $fname )
+        local highlight='pygmentize -l zsh'
+        if [[ -z ${commands[pygmentize]} ]]; then
+            printf 'Cannot find pygments.' >&2
+            highlight='cat'
+        fi
+        printf '%s\n' "$fdef" | ${(z)highlight}
     }
     
-    #MARK: - Function Source
-    function fn_src() {
-        # Check syntax.
-        SYNTAX=(fn src function_name)
-        if [[ -z $1 ]]; then
-            serror 'function_name' "$SYNTAX"; return 1
-        fi
-        
-        # Find function source file.
-        local fname=$1
+    ## src: find function source file ##
+    local function fn_src() {
         local fsource=$functions_source[$fname]
         if [[ -z $fsource ]]; then
-            echo "Definition file not found: '$(Bad $fname)'."
+            error "Definition file not found: '$(Bad $fname)'."
             return 1
         fi
         echo "$fsource"
         return 0
     }
     
+    ## isdef: check if a function is defined ##
+    function fn_isdef() {
+        if [[ ${+functions[$fname]} -ne 1 ]]; then
+            return 1
+        fi
+        return 0
+    }
     
-    # Primary script properties: function base,
-    # sub-command, and options.
-    typeset BASE                # fn
-    typeset -A optlist          # -flags and --options [option_value]
-    typeset COMMAND             # Command of ___FILEMNAME___ to invoke
-    
-    BASE=$( basename $0 )
-    get_options optlist "$@"
-    shift $optlist[shift_distance]
-    COMMAND=$1
-    
-    
-    # Compound command type.
-    case $COMMAND in
-        ## Print usage if 'fn' function
-        ## was called without any arguments.
-        '')
-            echo "Usage:"
-            echo "  $(b_bcyan $BASE) $(c 'command') $(underline $(cyan 'arguments'))$(b_magenta '...') - "\
-                 "invoke '$BASE command' function with some arguments."
-            ;;
-        
-        ## If command is specified, check that it exists and invoke it.
-        *)
-            shift
-            ${BASE}_${COMMAND} "$@"
-            exitcode=$?
-            if [[ $exitcode -eq 127 ]]; then
-                echo "Unknown command: $(Bad $COMMAND) (exit code: $exitcode)." >&2
+    ## sub: list functions defined within a function ##
+    function fn_sub() {
+        local srcfile
+        if ! srcfile=$( fn src $fname ); then
+            return 1
+        fi
+        prefix="${prefix:-${fname%%_*}}"
+        list=($( grep -E -o "${prefix}_\w+\(\)" $srcfile ))
+        for f in $list; do
+            local subfname=${f%'()'} # ${${f#${prefix}}%'()'}
+            if [[ ${+functions[$subfname]} ]]; then
+                printf '%s\n' "$subfname"
             fi
-            ;;
-    esac
+        done
+        return 0
+    }
     
-    return $exitcode
-}
+    ## commands: list function commands ##
+    function fn_commands() {
+        prefix="${prefix:-${fname%%_*}}"
+        local fcommands=(${$( fn -p ${prefix} sub $fname )//${prefix}_/})
+        printf '%s\n' $fcommands
+        return 0
+    }
+    
+    
+    
+    
+    # Options
+    typeset -A optlist
+    get_options_v2 optlist 'p:Ph' "$@" 2>/dev/null
+    shift $optlist[length]
+    
+    prefix="${optlist[p]}"
+    
+    # Function command
+    local cmd=$1
+    if [[ $# -eq 0 ]] || [[ -z $cmd ]] || [[ ${optlist[h]} == 'true' ]]; then
+        printf 'Available commands:\n'
+        printf "  $(cyan %s)\n" $( fn commands 'fn' )
+        return 0
+    fi
+    shift
+    
+    # Check command name
+    if ( ! functions | grep -w -e "fn_$cmd" &> /dev/null ); then
+        error "Unknown command: '$(Bad $cmd)'."
+        return 127;
+    fi
+    
+    # Command argument
+    fname="${@:1}"
+    if [[ $# -eq 0 ]]; then
+        error 'Function name not specified'
+        return 2
+    fi
+    
+    
+    if [[ $cmd == 'isdef' ]]; then
+        ${0}_${cmd} $fname
+        return $?
+    fi
+    
+    # Return if function is not defined
+    if [[ ${+functions[$fname]} -eq 0 ]]; then
+        error "Function '$(Bad $fname)' is not defined."
+        return 1
+    fi
+    
+    # Execute the command
+    autoload +X $fname
+    ${0}_${cmd} $fname
+    code=$?
+    
+    return $code
+)
