Z-Shell templates; bug fixes

diff --git a/zsh/functions/zshell/help b/zsh/functions/zshell/help
--- a/zsh/functions/zshell/help
+++ b/zsh/functions/zshell/help
@@ -8,14 +8,14 @@
 
 
 function help() {
-    local builtin_name=$1
-    local querry="help $1"
-    { printf '%s' "$querry" | sh } &> /dev/null
+    local querry=$1
+    local help_command="help $1"
+    { printf '%s' "$help_command" | sh } &> /dev/null
     if [[ $? -ne 0 ]]; then
-        printf 'Not found: %s.\n' "'$(Bad $querry)'"
+        printf 'Help not found: %s.\n' "'$(Bad $help_command)'" >&2
         return 1
     fi
-    local ret=$( printf '%s\n' "$querry" | sh )
-    local highlight_builtin_name=$( b_magenta "$builtin_name" )
-    printf '%s\n' "${ret//$builtin_name/$highlight_builtin_name}"
+    local ret=$( printf '%s\n' "$help_command" | sh )
+    local highlight_querry=$( b_magenta "$querry" )
+    printf '%s\n' "${ret//$querry/$highlight_querry}"
 }
diff --git a/zsh/templates/template_zfunction b/zsh/templates/template_zfunction
--- a/zsh/templates/template_zfunction
+++ b/zsh/templates/template_zfunction
@@ -1,1 +1,23 @@
-/Users/admin/Developer/Terminal/zsh/templates/template_zsh
+___SHEBANG___
+
+#  ___FILENAME___
+#  ___PACKAGE_NAME___
+#
+#  Created by ___USERNAME___ on ___DATE_FULL___.
+#  Copyright © ___DATE_YEAR___ ___OWNER___. All rights reserved.
+
+
+# <#Function description#>
+function ___FILENAME___() {
+    printf 'Template z-function: %s.\n' $(blue "$0")
+    
+    # Print to stderr
+    local def=$(fn src $0)
+    if [[ $? -ne 0 ]]; then
+        printf 'Definition not found.\n' >&2
+        return 1
+    fi
+    
+    printf 'Defined in: %s.\n' $(blue "$def")
+    return 0
+}
