[CS939-0628] 26 files changed, 1624 insertions(+), 609 deletions(-).
Signed-off-by: Maxim Puchkov <maxim_puchkov@sfu.ca>

diff --git a/zsh/functions/error b/zsh/functions/error
--- a/zsh/functions/error
+++ b/zsh/functions/error
@@ -18,40 +18,35 @@
 #       warning  'description...'
 #       error -0 'description...'
 function error() {
+#    setopt localtraps
     #MARK: - Data
-    # Error message label
-    typeset program_name='Error'
-    # Message
+    # Error message
     typeset message
     typeset message_title
     typeset message_desc
     # Exit code
-    typeset exit_code=1
+    typeset -i exit_code=1
     typeset exit_code_label
-    # Output
-    typeset output_device
-    typeset output_color=${error_color:-1}
-    # Output options
+    # Output format options
+    typeset -i output_color=${error_color:-1}
+    typeset split_lines='false'
     typeset autocapitalize='true'
     typeset remove_trailing_space='true'
     typeset trailing_period='true'
     typeset highlight_variables='true'
     
     
-    
-    
     #MARK: - Functions
     # Highlight all shell '$variables' in description
     function error-replace-variables() {
         # Placeholder label
-        typeset undefined_var_label
-        undefined_var_label='%F{3}undefined%f'
+#        typeset undefined_var_label
+#        undefined_var_label='%F{3}undefined%f'
         # Find and replace variables
         typeset find replace
         find='[$]([{(])?(([A-Za-z_][^ ]*)?[A-Za-z0-9!@#$%^&*=?_])([})])?'
-        replace="%F{1}\${\${\2}:-${(%)undefined_var_label}}%f"
+        replace="%F{1}\${\${\2}:-$text_labels[null]}%f"
         # Highlight variables in description
-        
         message_desc=$(/usr/bin/sed -E -e "s/${find}/${replace}/g" <<< "${argv}")
     }
     
@@ -62,16 +57,16 @@ function error() {
     # Title - text, color, and exit code
     function error-format-title() {
         if [[ $exit_code -gt 0 ]]; then
-            message_title="%F{$output_color}${program_name}%f"
-            exit_trap="return $exit_code;"
+            message_title="%F{${output_color}}${prog}%f"
+            exit_trap="return ${exit_code};"
         else
-            message_title='%F{3}Warning%f'
+            message_title="%F{3}${prog}%f"
             exit_trap='-'
         fi
         return 0
     }
     function error-plain-title() {
-        unfunction error-format-title
+        unset -f error-format-title
         function error-format-title() { return 0; }
     }
     
@@ -98,15 +93,13 @@ function error() {
         return 0
     }
     function error-plain-description() {
-        unfunction error-format-description
+        unset -f error-format-description
         function error-format-description() { return 0; }
     }
     
     # Message - title, description, and return status
     function error-format-message() {
-        error-format-title
-        error-format-description
-        message="%U${message_title}%u${exit_code_label}"
+        message="${message_title}${exit_code_label}"
         if [[ -n $message_desc ]]; then
             message="${message}: ${message_desc}"
         else
@@ -116,10 +109,10 @@ function error() {
     }
     # Format and print the error/warning message
     function error-print() {
+        error-format-title
+        error-format-description
         error-format-message
-        redbg $message >&2
-        print -P -- "$message" >${output_device:-/dev/stderr} ||
-        printf 'QQ<%q>QQ\n\n' "$message"
+        print -P -- "$message" >&2
         return 0
     }
     
@@ -127,17 +120,11 @@ function error() {
     
     
     #MARK: - Command Arguments
-    # Set program name
-    if [[ $0 != 'error' ]]; then
-        program_name=$0
-    fi
-    
-    # If the first argument is a digit prefixed by a '-',
-    # then 'error -123' is the same as 'error -e 123'
+    # Treat the very first flag as error code:
+    #   'error -123' == 'error -e 123'
     if [[ $1 =~ '^[-][0-9]+$' ]]; then
         set -- '-e' ${1#-} ${argv:2}
     fi
-    
     
     # Parse command arguments
     while [[ $1 =~ '^[-+]' ]] &&
@@ -149,23 +136,27 @@ function error() {
                 return 0
             ;;
             ## error -e: set the exit code ##
-            -e)
-                local -i code=$2
-                exit_code=$code
-                shift
+            -e) if [[ -n $2 ]] && [[ $2 =~ '^[0-9]+$' ]]; then
+                    exit_code=$2
+                    shift
+                else
+                    ( new_code=$2 \
+                    error -1 'exit code $new_code is invalid' )
+                    return $?
+                fi
             ;;
             ## error -c,--code: display exit code with error message ##
             -c|--code)
-                exit_code_label="%f [$exit_code]"
+                exit_code_label="%f [${exit_code}]"
             ;;
             ## error -D,--plain-description: do not format description ##
             -D|--plain-description)
                 error-plain-description
             ;;
-            ## error -n,--null: try to silence output messages ##
-            -n|--null)
-                output_device=/dev/null
-            ;;
+#            ## error -n,--null: try to silence output messages ##
+#            -n|--null)
+#                output_device=/dev/null
+#            ;;
             ## error -u,--usage: set title to 'Usage' ##
             -u|--usage)
                 error-plain-title
@@ -174,28 +165,33 @@ function error() {
             ;;
             ## error -t,--title: set error message title ##
             -t|--title)
-                if [[ -n $2 ]]; then
-                    error-plain-title
-                    message_title="%B%F{$output_color}${2}%f%b"
-                    shift
-                else
-                    break
+                if [[ -z $2 ]]; then
+                    error -1 'Error title is not set'
                 fi
+                error-plain-title
+                message_title="%F{${output_color}}${2}%f"
+                shift
             ;;
             
+            
             # Additional formatting options
-            ## error -a,--autocapitalize: capitalize first letter ##
-            ## error +a,--no-autocapitalize: do not capitalize first letter ##
+            ## error -S,--split-lines: capitalize first letter ##
+            ## error +S,--no-split-lines: do not capitalize first letter ##
+            -S|--split-lines)       split_lines='true'      ;;
+            +S|--no-split-lines)    split_lines='false'     ;;
+            
+            ## error -A,--autocapitalize: capitalize first letter ##
+            ## error +A,--no-autocapitalize: do not capitalize first letter ##
             -A|--autocapitalize)    autocapitalize='true'    ;;
             +A|--no-autocapitalize) autocapitalize='false'   ;;
             
-            ## error -p,--trailing-period: add trailing period ##
-            ## error +p,--no-trailing-period: do not add trailing period ##
+            ## error -P,--trailing-period: add trailing period ##
+            ## error +P,--no-trailing-period: do not add trailing period ##
             -P|--trailing-period)    trailing_period='true'  ;;
             +P|--no-trailing-period) trailing_period='false' ;;
             
-            ## error -h,--highlight: enable syntax highlighting ##
-            ## error +h,--no-highlight: disable syntax highlighting ##
+            ## error -H,--highlight: enable syntax highlighting ##
+            ## error +H,--no-highlight: disable syntax highlighting ##
             -H|--highlight)    highlight_variables='true'    ;;
             +H|--no-highlight) highlight_variables='false'   ;;
             
@@ -209,10 +205,26 @@ function error() {
     
     
     
-    # Set message description to the remaining arguments
-    message_desc="$@"
-    error-print && trap "$exit_trap" EXIT
+    # Display name
+    if [[ ! -v prog ]]; then
+        prog=${funcstack[2]:-${(C)0}}
+    fi
     
-    unfunction -m "${0}-*"
+    if [[ $exit_code -eq 0 ]]; then
+        default prog 'Warning'
+    fi
+    
+    # Set message description to the remaining arguments
+    if [[ $split_lines == 'true' ]]; then
+        message_desc=${(@F)argv}
+    else
+        message_desc=${argv}
+    fi
+    
+    # Print and exit
+    error-print && trap "print -- \${argv:0}; $exit_trap" EXIT
+    
+    unset -f -m "${0}-*"
+#    unset prog
     return $exit_code
 }
diff --git a/zsh/functions/list b/zsh/functions/list
--- a/zsh/functions/list
+++ b/zsh/functions/list
@@ -9,76 +9,111 @@
 
 # <#Function description#>
 function list() {
-    trap "
-        unfunction -m '${0}_*';
-        unfunction -m '__${0}_*';
-    " EXIT
-    
-    function __list_ls() {
-        typeset flags=$1
-        shift
-        script -q /dev/null command ls ${=flags} "$@"
-    }
-    function __list_grep() {
-        colorize_grep 'b_green' \
-            egrep --color='always' "$@"
-    }
-    
-    ## tc: time of creation ##
-    function list_tc() {
-        print_h1 'File creation time'
-        __list_ls -lFGHTUhrt "$@" |
-            __list_grep --regexp $time_regex
-    }
-    ## tch: time of change ##
-    function list_tch() {
-        print_h1 'File change time'
-        __list_ls -lFGHTchrt "$@" |
-            __list_grep --regexp $time_regex
-    }
-    ## tm: time of modification ##
-    function list_tm() {
-        print_h1 'Modification time'
-        __list_ls -lFGHThrt "$@" |
-            __list_grep --regexp $time_regex
-    }
-    ## ta: time of access ##
-    function list_ta() {
-        print_h1 'File access time'
-        __list_ls -lFGHThrtu "$@" |
-            __list_grep --regexp $time_regex
-    }
-    
-    ## f: file flags ##
-    function list_f() {
-        print_h1 'File flags'
-        () {
-            local flags=($(awk '{ print $5; }' "$1"))
-            shift
-            __list_ls -lFGHOh "$@" |
-                __list_grep --regexp " (${(j:|:)flags}) "
-        } =( command ls -lFGHOh "$@" ) "$@"
-    }
-    ## S: file size ##
-    function list_S() {
-        print_h1 'File size'
-        __list_ls -lFGHShr "$@" |
-            __list_grep --regexp '([0-9][\.0-9]*)[BKMG]'
-    }
-    
-    ## all: all files ##
-    function list_all() {
-        print_h1 'All files'
-        __list_ls -lFGHah "$@"
-    }
-    
-    
+    default base_options 'BFGHhk'
     default time_regex $(< $zdot/etc/ls-time.regex)
     
-    typeset cmd=${1:-'all'}
-    if ! isdef ${0}_${cmd}; then
-        error -127 "Command not found: %F{1}${cmd}%f."
-    fi
-    shift
-    ${0}_${cmd} "$@"
+    (
+        function header() {
+            builtin print -P -- "%B%K{11}%F{16} ${(U)argv}%b\t" \
+                "(ls${:- ${flags}}) %k%f" >&2
+        }
+        function do_ls() {
+            typeset flags=$1
+            shift
+            script -q /dev/null command ls ${=flags} "$@"
+        }
+        function do_grep() {
+            colorize_grep 'b_green' \
+                egrep --color='always' "$@"
+        }
+        
+        ## tc: time of creation ##
+        function list_tc() {
+            flags="-lTUrt${base_options}"
+            header 'File creation time'
+            do_ls $flags "$@" |
+                do_grep --regexp $time_regex
+        }
+        ## tch: time of change ##
+        function list_tch() {
+            flags="-lTcrt${base_options}"
+            header 'File change time'
+#            do_ls -lFGHTchrt "$@" |
+            do_ls $flags "$@" |
+                do_grep --regexp $time_regex
+        }
+        ## tm: time of modification ##
+        function list_tm() {
+            flags="-lTrt${base_options}"
+            header 'Modification time'
+#            do_ls -lFGHThrt "$@" |
+            do_ls $flags "$@" |
+                do_grep --regexp $time_regex
+        }
+        ## ta: time of access ##
+        function list_ta() {
+            flags="-lTrtu${base_options}"
+            header 'File access time'
+#            do_ls -lFGHThrtu "$@" |
+            do_ls $flags "$@" |
+                do_grep --regexp $time_regex
+        }
+
+        ## f: file flags ##
+        function list_f() {
+            flags="-lO${base_options}"
+            header 'File flags'
+            () {
+                local awk_flags=($(awk '{ print $5; }' "$1"))
+                shift
+                do_ls $flags "$@" |
+                    do_grep --regexp " (${(j:|:)awk_flags}) "
+            } =( command ls $flags "$@" ) "$@"
+        }
+        ## S: file size ##
+        function list_S() {
+            flags="-lSr${base_options}"
+            header 'File size'
+            do_ls -lFGHShr "$@" |
+                do_grep --regexp '([0-9][\.0-9]*)[BKMG]'
+        }
+        
+        ## all: all files ##
+        function list_all() {
+            flags="-la${base_options}"
+            header 'All files'
+            do_ls $flags "$@"
+        }
+        
+        
+        
+        typeset -A optlist
+        autoload -Uz get-arguments
+        get-arguments -A optlist -f 'h' -- $argv
+        
+        if [[ $optlist[-h] -eq 1 ]]; then
+            fn print-commands $0
+            return 0
+        fi
+        
+        
+        # When 'list' is run without arguments,
+        # run the 'list all' command
+        typeset cmd
+        if [[ -n $1 ]]; then
+            cmd=$1
+            shift
+        else
+            cmd='all'
+        fi
+        
+        # Check that command is defined
+        if [[ ${+functions[${0}_${cmd}]} -ne 1 ]]; then
+            error -127 'Command not found: $cmd.'
+            fn print-commands $0
+        fi
+        ${0}_${cmd} "$@"
+    )
+    
+    return $?
 }
diff --git a/zsh/site-functions/get-arguments b/zsh/site-functions/get-arguments
--- a/zsh/site-functions/get-arguments
+++ b/zsh/site-functions/get-arguments
@@ -15,8 +15,6 @@
 #     [-[Aa] array_id]
 #     [-f name[, ...]]
 #     [-o name[, ...]]
-#     [
-#     [[-+]u]
 #   --
 #     args
 #
@@ -27,10 +25,12 @@
 #
 # Examples:
 # 1. Parse options X,Y,Z and store their values in 'optlist':
-#       get-arguments -o X,Y,Z -- -Z opt-Z -X opt-x -Y opt-y
+#       set -- -Z opt-Z -X opt-x -Y opt-y
+#       get-arguments -o X Y Z -- $argv
 # 2. Parse flags A,B, options C,D, and store result in 'myArray':
+#       set --  -C opt-C -A -D opt-D -B
 #       typeset -A myArray
-#       get-arguments -A myArray -f A,B -o C,D -- -C opt-C -A -D opt-D -B
+#       get-arguments -A myArray -f A B -o C D -- $argv
 function get-arguments() {
     # Load 'zsh/zutil' module
     local zsh_module='zsh/zutil'
@@ -43,15 +43,14 @@ function get-arguments() {
     local -i delimiter_index=${argv[(i)$delimiter]}
     # Missing '--' argument delimiter
     if [[ $delimiter_index -gt $# ]]; then
-        error -1 "Argument specification and argument values must be delimited with two dashes '\$delimiter':" \
-        "\n '%B${0}%b -o o1,o2,o3 \$delimiter -o1 X -o2 Y -o3 Z other args'"
+        error -1 \
+            "Argument %Uspecification%u and argument %Uvalues%u must be delimited with two dashes '\$delimiter':" '\n' \
+            "'%B${0}%b %U-f a b c -o x y z%u \$delimiter %U-a -x X -y Y other args%u"
     fi
     # If delimiter '--' is the last argument, there is nothing to parse
     if [[ $delimiter_index -eq $# ]]; then
         return 1
     fi
-    
-    
     
     
     #MARK: - Parameters for 'get-arguments'
@@ -73,18 +72,13 @@ function get-arguments() {
     
     
     #MARK: - Set 'get-arguments' Options
-    # Parameters of the current option
-    local -i last_index
-    local -a list
-    
-    # Parse all arguments which begin with '-' or '+'
+    # Parse arguments which begin with '-'
+    # or '+' (command options)
     while [[ $1 =~ '^[-+]' ]] &&
           [[ $1 != '--' ]]; do
-#        S "next 1=<$1>\n"
-#        red $(S "ALL: <$argv>")
-        
-        # Find the last argument index of the current option,
-        # and set 'list' to all current arguments
+        # Arguments until the next command option
+        # are parameters for the current option
+        local -a list=()
         let last_index=${${argv:2}[(i)[-+]*]}
         set -A list ${argv[2,$last_index]}
 #        print -P "List is {$list}[$#list]"
@@ -92,15 +86,6 @@ function get-arguments() {
         case $1 in
             # Flags
             -f|--flags)
-                
-#                ( red "RED [$#] $argv"
-#                shift;
-#                red "Len=$#list"
-#                shift $#list
-#                red "RED [$#] $argv"
-#                redbg "num 1 is now $1"
-#                yellowbg "Added $#list elements: {$list}"
-#                 )
                 shift
                 flag_names+=($list)
                 shift ${#list}
@@ -110,6 +95,9 @@ function get-arguments() {
             -o|--opts|--options)
                 shift
                 local opt_spec=''
+                typeset -ag copy
+                copy=($list)
+                
                 for opt_spec in $list; do
                     case $opt_spec in
                         *:*)
@@ -128,8 +116,6 @@ function get-arguments() {
             # Specify output array name and type
             -A|-a)
                 array_type=$1
-                unset $array_id
-                typeset $array_type -g $array_id
                 array_id=$2
                 shift 2
             ;;
@@ -137,13 +123,9 @@ function get-arguments() {
             # Stop parsing parameters
             *)  break ;;
         esac
-
     done
-#    S "end is $argv"
-    # Skip '--'
-    if [[ $1 == '--' ]]; then
-        shift
-    fi
+    [[ $1 == '--' ]] && shift
+    
     
     # Exit if no flag or option names were recognized
     if [[ -z $flag_names ]] &&
@@ -152,45 +134,46 @@ function get-arguments() {
     fi
     
     
-    # Recognized options and options with default values
-    typeset -a {opts,def}_keys
-    opts_keys=(${(k)opts})
-    def_keys=(${(Mk)defaults:#-*})
     
+    
+    
+    #MARK: - Parse Arguments
     # Recognized flags/options
     typeset -a flags
     typeset -A opts
     flags=()
     opts=()
-    
-    # Non-recognized flags/options
-    typeset -a unset_{flags,opts}
-    unset_opts=(${${:-'-'${^option_names}}:|opts_keys})
-    unset_flags=(${${:-'-'${^flag_names}}:|flags})
-    
-    
-    
-    
-    #MARK: - Parse Arguments
     # Set 'specs' for the 'zparseopts' builtin
     typeset -a specs
     specs=(
         ${^flag_names}'=flags'
         ${^option_names}':=opts'
     )
-    # Store parsed flags
-    builtin zparseopts -D -E -- ${=specs} &>/dev/null
-    if [[ $? -ne 0 ]]; then
-        error -1 "Parse failure: 'zparseopts'."
+    
+    # Parse parameters
+    builtin zparseopts -D -E -- $specs &>/dev/null
+    local -i parse_status=$?
+    if [[ $parse_status -ne 0 ]] then
+        ( name='zparseopts' \
+            error -$parse_status -c "Invalid '%U\${name}%u' specs: {\${specs}}." )
     fi
+    
+    # Recognized options and options with default values
+    typeset -a {opts,def}_keys
+    opts_keys=(${(k)opts})
+    def_keys=(${(Mk)defaults:#-*})
+    # Non-recognized flags/options
+    typeset -a unset_{flags,opts}
+    unset_opts=(${${:-'-'${^option_names}}:|opts_keys})
+    unset_flags=(${${:-'-'${^flag_names}}:|flags})
     
     # Set remaining arguments of the caller
     typeset -a rest
     set -A rest ${(qq)argv}
     trap "{
-        builtin set -- $rest &&
+        set -- $rest &&
         [[ \$1 == '--' ]] &&
-        builtin shift
+        shift
     }" EXIT
     
     
