Update zsh functions

diff --git a/zsh/functions/error b/zsh/functions/error
--- a/zsh/functions/error
+++ b/zsh/functions/error
@@ -17,8 +17,7 @@
 #     and continue without returning any value.
 #       warning  'description...'
 #       error -0 'description...'
-function error() {
-#    setopt localtraps
+function error() {(
     #MARK: - Data
     # Error message
     typeset message
@@ -29,19 +28,20 @@ function error() {
     typeset exit_code_label
     # Output format options
     typeset -i output_color=${error_color:-1}
+    typeset -i output_color_2=${warning_color:-3}
     typeset split_lines='false'
     typeset autocapitalize='true'
     typeset remove_trailing_space='true'
     typeset trailing_period='true'
     typeset highlight_variables='true'
+    typeset return_on_exit='true'
+    
+    
     
     
     #MARK: - Functions
     # Highlight all shell '$variables' in description
     function error-replace-variables() {
-        # Placeholder label
-#        typeset undefined_var_label
-#        undefined_var_label='%F{3}undefined%f'
         # Find and replace variables
         typeset find replace
         find='[$]([{(])?(([A-Za-z_][^ ]*)?[A-Za-z0-9!@#$%^&*=?_])([})])?'
@@ -50,18 +50,13 @@ function error() {
         message_desc=$(/usr/bin/sed -E -e "s/${find}/${replace}/g" <<< "${argv}")
     }
     
-    
-    
-    
     #MARK: Format
     # Title - text, color, and exit code
     function error-format-title() {
-        if [[ $exit_code -gt 0 ]]; then
+        if [[ $exit_code -ne 0 ]]; then
             message_title="%F{${output_color}}${prog}%f"
-            exit_trap="return ${exit_code};"
         else
-            message_title="%F{3}${prog}%f"
-            exit_trap='-'
+            message_title="%F{$output_color_2}${prog}%f"
         fi
         return 0
     }
@@ -73,10 +68,13 @@ function error() {
     # Description - capitalization, trailing period, highlight
     function error-format-description() {
         message_desc="${message_desc:-No description.}"
-        if [[ $autocapitalize == 'true' ]]; then
+        [[ $autocapitalize == 'true' ]] &&
             message_desc="${(C)message_desc[1]}${${message_desc:1}}"
-        fi
+#        if [[ $autocapitalize == 'true' ]]; then
+#            message_desc="${(C)message_desc[1]}${${message_desc:1}}"
+#        fi
         if [[ $remove_trailing_space == 'true' ]]; then
+            
             if [[ $message_desc[-1] == ' ' ]]; then
                 message_desc="${message_desc% *}"
             fi
@@ -108,11 +106,11 @@ function error() {
         return 0
     }
     # Format and print the error/warning message
-    function error-print() {
+    function error-format() {
         error-format-title
         error-format-description
         error-format-message
-        print -P -- "$message" >&2
+#        print -P -- "$message" >&2
         return 0
     }
     
@@ -140,8 +138,7 @@ function error() {
                     exit_code=$2
                     shift
                 else
-                    ( new_code=$2 \
-                    error -1 'exit code $new_code is invalid' )
+                    ( new_code=$2 error -1 'Exit code $new_code is invalid' )
                     return $?
                 fi
             ;;
@@ -153,10 +150,6 @@ function error() {
             -D|--plain-description)
                 error-plain-description
             ;;
-#            ## error -n,--null: try to silence output messages ##
-#            -n|--null)
-#                output_device=/dev/null
-#            ;;
             ## error -u,--usage: set title to 'Usage' ##
             -u|--usage)
                 error-plain-title
@@ -195,6 +188,8 @@ function error() {
             -H|--highlight)    highlight_variables='true'    ;;
             +H|--no-highlight) highlight_variables='false'   ;;
             
+            [-+]R|--(no-|)return) return_on_exit=$(boolopt $1 'true' 'false') ;;
+            
             # Stop parsing options
             *)  break ;;
         esac
@@ -203,9 +198,7 @@ function error() {
     [[ $1 == '--' ]] && shift
     
     
-    
-    
-    # Display name
+    # Set display name
     if [[ ! -v prog ]]; then
         prog=${funcstack[2]:-${(C)0}}
     fi
@@ -222,9 +215,11 @@ function error() {
     fi
     
     # Print and exit
-    error-print && trap "print -- \${argv:0}; $exit_trap" EXIT
-    
+    error-format
+    notify -P -- $message >&2
+    if [[ $return_on_exit == 'true' ]]; then
+        trap 'return '${exit_code}';' EXIT
+    fi
     unset -f -m "${0}-*"
-#    unset prog
     return $exit_code
-}
+)}
diff --git a/zsh/functions/retc b/zsh/functions/retc
--- a/zsh/functions/retc
+++ b/zsh/functions/retc
@@ -7,40 +7,60 @@
 #  Copyright © 2020 Maxim Puchkov. All rights reserved.
 
 
-# Print return code(s) of the last command or pipe.
-function retc() {
-    # Last status codes
-    typeset -a last_pipestatus=(${pipestatus})
-    local length index value
-    length=${#last_pipestatus}
+# Print return code of the last command.
+function retc() {(
+    escseq() {
+        printf '\e[%dm' $1
+    }
+
+    let code=$?
     
-    # Set color of status code 0 to green; status
-    # codes greater than 0 - to red
-    index=1
-    while [[ $index -le $length ]]; do
-        value=${last_pipestatus[$index]}
-        value="%F{%(${value}?:2:1)}${value}%f"
-        # Underline the very last status code
-        if [[ $index -eq $length ]]; then
-            value="%U${value}%u"
-        fi
-        last_pipestatus[$index]=${(%)value}
-        index=$(( $index + 1 ))
-    done
+    dim=$(escseq 2)
+    color=$code
+    nocolor=39
+    nodim=$(escseq 9)
     
-    # Set message label and description
-    typeset label description
-    if [[ $length -eq 1 ]]; then
-        label='Status code'
-    else
-        label='Pipe status'
-    fi
-    description=${(j:, :)last_pipestatus}
-    
-    # Additional formatting when outputting to terminal
-    if [[ -t 1 ]]; then
-        label="%B${label}%b"
-    fi
-    
-    builtin print -P -- "${label}: ${description}."
-}
+    printf '%b--- Return code: %b%d%b ---%b\n' \
+        $dim $color $code $nocolor $nodim
+   return $code
+   
+#    print -P -- "--- Return code: %F{%(?.2.1)}%?%f ---"; #&& print "return $?"
+)}
+
+
+#function retc() {
+#    # Last status codes
+#    typeset -a last_pipestatus=(${pipestatus})
+#    local length index value
+#    length=${#last_pipestatus}
+#
+#    # Set color of status code 0 to green; status
+#    # codes greater than 0 - to red
+#    index=1
+#    while [[ $index -le $length ]]; do
+#        value=${last_pipestatus[$index]}
+#        value="%F{%(${value}?:2:1)}${value}%f"
+#        # Underline the very last status code
+#        if [[ $index -eq $length ]]; then
+#            value="%U${value}%u"
+#        fi
+#        last_pipestatus[$index]=${(%)value}
+#        index=$(( $index + 1 ))
+#    done
+#
+#    # Set message label and description
+#    typeset label description
+#    if [[ $length -eq 1 ]]; then
+#        label='Status code'
+#    else
+#        label='Pipe status'
+#    fi
+#    description=${(j:, :)last_pipestatus}
+#
+#    # Additional formatting when outputting to terminal
+#    if [[ -t 1 ]]; then
+#        label="%B${label}%b"
+#    fi
+#
+#    builtin print -P -- "${label}: ${description}."
+#}
diff --git a/zsh/site-functions/get-arguments b/zsh/site-functions/get-arguments
--- a/zsh/site-functions/get-arguments
+++ b/zsh/site-functions/get-arguments
@@ -35,7 +35,7 @@ function get-arguments() {
     # Load 'zsh/zutil' module
     local zsh_module='zsh/zutil'
     if ! zmodload -e $zsh_module; then
-        error -127 'Cannot load zsh module: $zsh_module.'
+        error -1 'Cannot load zsh module: $zsh_module.'
     fi
     
     # Find argument specification and value delimiter
@@ -81,7 +81,6 @@ function get-arguments() {
         local -a list=()
         let last_index=${${argv:2}[(i)[-+]*]}
         set -A list ${argv[2,$last_index]}
-#        print -P "List is {$list}[$#list]"
         
         case $1 in
             # Flags
@@ -95,9 +94,6 @@ function get-arguments() {
             -o|--opts|--options)
                 shift
                 local opt_spec=''
-                typeset -ag copy
-                copy=($list)
-                
                 for opt_spec in $list; do
                     case $opt_spec in
                         *:*)
@@ -145,10 +141,7 @@ function get-arguments() {
     opts=()
     # Set 'specs' for the 'zparseopts' builtin
     typeset -a specs
-    specs=(
-        ${^flag_names}'=flags'
-        ${^option_names}':=opts'
-    )
+    specs=( ${^flag_names}'=flags' ${^option_names}':=opts' )
     
     # Parse parameters
     builtin zparseopts -D -E -- $specs &>/dev/null
@@ -168,13 +161,7 @@ function get-arguments() {
     unset_flags=(${${:-'-'${^flag_names}}:|flags})
     
     # Set remaining arguments of the caller
-    typeset -a rest
-    set -A rest ${(qq)argv}
-    trap "{
-        set -- $rest &&
-        [[ \$1 == '--' ]] &&
-        shift
-    }" EXIT
+    trap '{ set -- '"$argv"'; [[ $1 == "--" ]] && shift; }' EXIT
     
     
     
@@ -202,7 +189,7 @@ function get-arguments() {
         default_value=${defaults[(k)$name]}
         given_value=${result[(k)$name]}
         if [[ -n $default_value ]] &&
-           [[ -z $given_value   ]]; then
+           [[ -z $given_value ]]; then
             result+=( [$name]=$default_value )
         fi
     done
@@ -210,381 +197,8 @@ function get-arguments() {
     
     # Set the output [associative] array to the
     # (name, value) pairs of result array
-#    print -l -- "unset $array_id" \
-#        "typeset $array_type -g $array_id" \
-#        "set -A $array_id ${(kv)result}"
-    
     unset $array_id
     typeset $array_type -g $array_id
     set -A $array_id ${(kv)result}
     return 0
 }
-
-
-
-
-
-
-
-
-
-#function get-arguments() {
-#    # Load 'zsh/zutil' module
-#    local zsh_module='zsh/zutil'
-#    if ! zmodload -e $zsh_module; then
-#        error -127 'Cannot load zsh module: $zsh_module.'
-#    fi
-#    # Find argument specification and value delimiter
-#    local delimiter='--'
-#    if [[ ${argv[(i)$delimiter]} -gt $# ]]; then
-#        error -1 "Argument specification and argument values must be delimited with two dashes '\$delimiter':" \
-#        "\n '%B${0}%b -o o1,o2,o3 \$delimiter -o1 X -o2 Y -o3 Z other args'"
-#    fi
-#
-#
-##            defaults+=( ${(@fs/:/q):-'opt-'${(P)^list_id}} )
-##            typeset -Ag zzz
-##            zzz=("${(Ps/:/)list_id}")
-##            print -- ${(Ps/:/)list_id}
-#
-#    function get-arguments-parse-default-specs() {
-#        typeset list_id=$1
-#        typeset list_size=${(Pkv)#list_id}
-#        print-var list_id list_size
-#        print -Pl -- "%F{3}"${(Pkv)list_id}"%f"
-#        if [[ $list_size -eq 0 ]] ||
-#           [[ $(( $list_size % 2 )) -ne 0 ]]; then
-#            return 1
-##            error -2 'Invalid list'
-#        fi
-#        typeset -A arr
-#        set -A arr ${(Pkv)list_id}
-#
-#        if [[ $#arr -eq 0 ]]; then
-#            error -1 'invalid id: $list_id'
-#        fi
-##        list_values=()
-#        for arg value in ${(Pkv)list_id}; do
-#            arr+=( [-$arg]=$value )
-#        done
-#
-##        S $defaults
-#        return 0
-#    }
-#
-#    #MARK: - Parse Flag/Option Names
-#    # Parse list of argument names and calculate
-#    # shift distance
-#    typeset -a name_list
-#    typeset -i distance
-##    function get-arguments-parse-name-list() {
-##        distance=0
-##        # Type (flag or option)
-##        local name_type=$1
-##        shift
-##        distance=$(( $distance + 1 ))
-##        if [[ -z $1 ]]; then
-##            error -1 "Cannot parse argument for '\$name_type.'"
-##        fi
-##
-##        # List of individual names
-##        name_list=()
-##        if [[ $1 =~ '[,]' ]]; then
-##            # Add each comma-separated
-##            # argument to the list
-##            while [[ $1 =~ '[,]' ]]; do
-##                name_list+=($1)
-##                distance=$(( $distance + 1 ))
-##                if [[   $1 =~ '[,][ ]?$' ]] &&
-##                   [[ ! $2 =~ '[,]' ]]; then
-##                    name_list+=($2)
-##                    distance=$(( $distance + 1 ))
-##                    break
-##                fi
-##            shift
-##            done
-##        else
-##            # If an argument does not contain commas,
-##            # then it is the only argument
-##            name_list+=($1)
-##            distance=$(( $distance + 1 ))
-##        fi
-##        return 0
-##    }
-##
-#
-#
-#    #MARK: - Parameters for 'get-arguments'
-#    # Names of flags and options
-#    unset flag_names option_names
-#    typeset -aUg flag_names option_names
-#    # Result array
-#    unset array_{id,type}
-#    typeset array_{id,type}
-#    array_id='optlist'
-#    array_type='-A'
-#    # Default values
-#    typeset -Ag defaults
-#    defaults=( [flag-set]=1
-#               [flag-unset]=0
-#               [opt-unset]="''" )
-#    typeset def_{spec,value}
-#
-#    # Options
-#    ## get-arguments [-+]u: append unset flags [default: off] ##
-#    typeset -i include_unset_arguments=0
-#
-#
-#    #MARK: - Parse Names and Settings
-#    # Parse flag and option names
-#    while [[ $1 =~ '^[\+\-]' ]] &&
-#          [[ $1 != '--' ]]; do
-##        yellow "arg is $1"
-#print "Number one is $1"
-#        redbg "***********"; redbg "***********"
-#        print -- "argv=[$argv], argc=[${#argv}], 1=[$1]"
-#        redbg "***********"; redbg "***********"
-##        magenta "other args are $2 , $3 , $4"
-#        case $1 in
-#            -f|--flags)
-#                shift
-#                typeset -ag names
-#                local index=$(( ${argv[(i)[-+]*]} - 1 ))
-#                names=(${argv[1,$index]})
-#                shift $index
-#                print -l -- $names
-#                flag_names+=($names)
-#            ;;
-##            # Flags
-##            -f|--flags)
-##                shift
-##                while [[ ! $1 =~ '^[\+\-]' ]]; do
-##                blue $1
-##                    if [[ $1 =~ '^(.+):([\+\-]|[0-1])' ]]; then
-##                        name=${1%:*}
-##                        value=${1#*:}
-##                        red $name
-##                        green $value
-##                        case ${1/#*:} in
-##                            1|-) value=1 ; redbg $1 - $value ;;
-##                            *)   value=0 ;;
-##                        esac
-##shift
-##                    else
-##                        name=${1%:*}
-##                        value=${defaults[flag-set]}
-##                        blue $name
-##                        cyan $value
-##                    fi
-##                    print $name
-##                    print $value
-##                    S "WAIT"
-##                    read
-##                    defaults+=( [-$name]=$value )
-##                    flag_names+=($name)
-##                    shift
-##                done
-##                print-var @
-##            ;;
-##            # Options
-##            -o|--opts|--options)
-##                shift
-##                redbg start at o
-##                while [[ ! $1 =~ $'^[\-\+]' ]]; do
-##                S $1
-##                    if [[ $1 =~ '^(.+):(.+)' ]]; then
-##                        name=${1%:*}
-##                        value=${1#*:}
-##                        defaults+=( [-$name]=$value )
-##                    else
-##                        name=${1%:*}
-##                    fi
-##                    option_names+=($name)
-##                    shift
-##                done
-##                print-var @
-##            ;;
-#
-#            # Set output array name and type
-#            -A|-a)
-#                print "ARRAY TYPE $1"
-#                array_type=$1
-#                shift
-#                print "ARRAY ID $1"
-#                typeset $array_type -g $array_id
-#                print ${(Pt)array_id}
-#                array_id=$1
-##                bluebg $array_type
-##                cyanbg $array_id
-#red ${(P)array_id}
-#                unset $array_id
-#                typeset $array_type -g $array_id
-##                print -l -- $array_id
-##                set -A $array_id
-##                set -A $array_id
-#                shift
-##                S $array_type __ __ $array_id
-#            ;;
-#
-#            # When enabled (-u), append unset
-#            # arguments to the result array
-#            [-+]u)
-#                include_unset_arguments=$(opt-mode "$1")
-#                shift
-#            ;;
-#
-#            # Stop parsing parameters
-#            *)  print "break at $1, $argv, $#";  read; break ;;
-#        esac
-#        S "end of esac : $1"
-#        print -P -- "%K{2}${(j:, :)argv}%k\n\n"
-#        print-line
-#    done
-#    # Skip '--'
-#    if [[ $1 == '--' ]]; then
-#        shift
-#    fi
-#    # Check that more arguments are remaining
-#    if [[ $# -eq 0 ]]; then
-#        error -1 'Invalid argument values.'
-#        return 1
-#    fi
-#    # Check all parsed flag/option names
-#    if [[ -z $flag_names ]] &&
-#       [[ -z $option_names ]]; then
-#        error -1 'Missing descriptions of flags and/or options.'
-#    fi
-#     redbg 125
-#
-##    get-arguments-parse-default-specs flag_names
-##    get-arguments-parse-default-specs option_names
-#
-#    unfunction -m "${0}-*"
-#
-#
-#    #MARK: - Parse Arguments with 'zparseopts'
-#    # Initialize 'flags' and 'opts' arrays
-##    typeset -ag {unset_,}flags {unset_,}opts
-##    unset_flags=();  flags=()
-##    unset_opts=();   opts=()
-##    typeset -a {,unset_}{flags,opts}
-#    typeset -a flags
-#    typeset -a unset_flags
-#    typeset -A opts
-#    typeset -a unset_opts
-#    # Set 'specs' for the zparseopts builtin
-#    typeset -a specs
-#    S "All Flag names: <$flag_names>."
-#    echo; echo
-#    S "All Opt names: <$option_names>."
-#
-#    specs=(
-#        ${^flag_names}'=flags'
-#        ${^option_names}':=opts'
-#    )
-#
-#    greenbg "***********"; greenbg "***********"
-#    print -- "argv=[$argv], argc=[${#argv}], 1=[$1]"
-#    greenbg "***********"; greenbg "***********"
-#
-#    print-var argv flag_names option_names unset_opts unset_flags
-#    # Parse and store recognized flags and options
-#    builtin zparseopts -D -E -- ${=specs} &>/dev/null
-#    if [[ $? -ne 0 ]]; then
-#        error -1 'Failed to parse options.'
-#    fi
-# redbg 124
-#    # Set remaining arguments of the caller
-#    typeset -a rest
-#    set -A rest ${(qq)argv}
-#    trap "
-#        builtin set -- $rest;
-#        [[ \$1 == '--' ]] && builtin shift;
-#    " EXIT
-#
-#
-#    redbg 123
-#
-#    #MARK: - Set the Result Array
-#    typeset -A result
-#    result=()
-#
-#    # List of unset flag/option names
-#    local -a opts_keys
-#    opts_keys=(${(k)opts})
-#    unset_opts=(${${:-'-'${^option_names}}:|opts_keys})
-#    unset_flags=(${${:-'-'${^flag_names}}:|flags})
-#
-#    # Append unset options and flags to the result array
-#    # unless '-u' flag is set.
-#    local name value
-#    if [[ $include_unset_arguments -eq 1 ]]; then
-#        for name in $unset_flags; do
-#            value=${defaults[flag-unset]}
-#            result+=( [$name]=$value )
-#        done
-#        for name in $unset_opts; do
-#            value="${defaults[opt-unset]}"
-#            result+=( [$name]=$value )
-#        done
-#    fi
-#
-#    # Append all set options from 'opts' to 'result'
-##    result+=(${(kv)opts})
-##    set -A result ${(kv)opts}
-#    yellowbg $result
-#    result+=(${(kv)opts})
-#    yellowbg $result
-#    echo
-##    set -A result ${flags}
-#    print-var flags @
-#    print-var result optlist
-#    print-line
-#
-#    # Append all set flags to 'result' as options
-#    # with a value (default value: 1)
-#    for name in $flags; do
-#        result+=( [$name]=${defaults[flag-set]} )
-#    done
-##
-##    for name in ${flag_names}; do
-##        print -- ">> adding $name as result[-$name]=${defaults[flag-set]}."
-##        result+=( [-$name]=${defaults[flag-set]} )
-##    done
-#    print-var opts
-#    for name value in ${(kv)opts}; do
-#        print -- ">> adding $name, $value as result[-$name]=$value."
-#        result+=( [-$name]=$value )
-#    done
-#
-#
-##    missing_flags=(${${:-'-'${^flag_names}}:|flags})
-##    unset_flags=(${^${:-'-'${^flag_names}}:|flags}' '$flag_unset)
-##    print-var option_names opts
-##    unset_opts=(${^${:-'-'${^option_names}}:|options}' '$flag_unset)
-##
-##    result+=( ${=unset_flags} ${=unset_options} )
-#
-##    missing_flags=(${:-'-'${^flag_names}}:|flags})
-##    missing_flags=(${:-'-'${^flag_names}:|flags})
-##
-##    for flag in $unset_flags; do
-##        opts+=( [$flag]=$flag_unset )
-##    done
-#
-#    redbg "Result is ${#result}"
-#    read -k1
-#    # Assign options to the result array
-##    unset $array_id
-##    typeset $array_type -g $array_id
-##    typeset $array_type
-##    print -l -- ${(kv)result}
-##    bluebg ${(kv)result} ---- ${#result}
-##}
-#
-#    set -A $array_id ${(kv)result}
-##    print-var $array_id
-##    print-var array_id result
-#
-#    return 0
-#}
