Z-Shell functions update

diff --git a/zsh/functions/fn b/zsh/functions/fn
--- a/zsh/functions/fn
+++ b/zsh/functions/fn
@@ -8,14 +8,15 @@
 
 
 # Information about shell functions.
-
+#
 # Options:
 ## -h,--help: show help ##
 function fn() (
     ## def: print function definition ##
     function fn_def() {
-        print -P -N -- "%Ufunction%u "
-        functions $fn_name | highlight
+        local label="function %U%B${fn_name}%b%u () {"
+        local def="$(functions $fn_name | highlight | tail -n +2 )"
+        printf '%s\n%s\n' "${(%)label}" "$def"
         return $?
     }
     ## src: find function source file ##
@@ -37,8 +38,10 @@ function fn() (
     function fn_show() {
         local code=$(fn def $fn_name)
         local file=$(fn src $fn_name)
-        printf '%s\n\n' "$code"
-        print -Pf '%s\n' "%U${(D)file}%u"
+        local line=${(%):-"%F{8}${(l:$COLUMNS::-:)}%f"}
+        print -f '%s\n%s\n%s\n\nFile: %s\n' "$line" "$code" "$line" "${(D)file}"
+#        print -f '%s\n\n' "$code"
+#        print -Pf 'File: %s\n' "%U${(D)file}%u"
         return 0
     }
     ## open: open function source file ##
@@ -60,16 +63,17 @@ function fn() (
     }
     ## sub: list functions defined within a function ##
     function fn_sub() {
-        name_prefix="${name_prefix:-${fn_name%%_*}}"
+        name_prefix="${name_prefix:-${fn_name%%[_-]*}}"
         typeset srcfile
         if ! srcfile=$( fn src $fn_name ); then
             return 1
         fi
+        typeset fn_syntax fn_pattern
+        fn_syntax="${name_prefix}_((?:\w|-)+)"
+        fn_pattern="^[^#]*(function\s+${fn_syntax}|${fn_syntax}\s*\(\))\s*"
         typeset -a list
-        list=($( egrep --only-matching \
-                       --ignore-case \
-                       --regexp "${name_prefix}_(\w|\-)+\(\s*\)" -- \
-                       $srcfile ))
+        list=($( egrep -o -i -E "${fn_pattern}" -- $srcfile ))
+        list=(${${list#'function'*}%*'()'})
         typeset f
         for f in $list; do
             typeset subfn_name=${f%'('*')'}
@@ -95,6 +99,10 @@ function fn() (
     }
     ## options: list function flags and options ##
     function fn_options() {
+        typeset srcfile
+        if ! srcfile=$( fn src $fn_name ); then
+            return 1
+        fi
         typeset grep_pattern='^[ ]*##[ ]*-[^ ]+: .* ##[ ]*$'
         typeset sed_pattern='s/## ([-].*): (.*) ##/\1: \2/p'
         typeset -A reply
@@ -145,27 +153,36 @@ function fn() (
     
     
     
-    # Completion for commands
-    function fn_commands_completion() {
-        if
-        typeset -A reply
-        typeset file=$1
-        typeset -a fn_commands=($(fn -p ${file:t} commands ${file:t}))
-        # Parse commands
-        for cmd in $fn_commands; do
-            local pattern="## ${cmd}: .+ ##.*function ${fn_name}[\-\_]${cmd}[\s]*\(\)"
-            local description=$(
-                greps '-o' "$pattern" "$file" |
-                    head -n 1 |
-                    sed -e "s/## ${cmd}: //g" -e "s/ ##.*//g"
-            )
-            reply[$cmd]="${description:-''}"
-        done
-        # Print command completion
-        for k v in ${(kv)reply}; do
-            printf '\t%s:"%s"\n' "$k" "$v" | colrm
-        done
-    }
+#    # Completion for commands
+#    function fn_commands_completion() {
+#        typeset -a arg
+#        while read -t -E -A arg; do
+#            S $arg
+#
+#            blue
+#
+#
+#        done
+#
+#
+#        typeset -A reply
+#        typeset file=$1
+#        typeset -a fn_commands=($(fn -p ${file:t} commands ${file:t}))
+#        # Parse commands
+#        for cmd in $fn_commands; do
+#            local pattern="## ${cmd}: .+ ##.*function ${fn_name}[\-\_]${cmd}[\s]*\(\)"
+#            local description=$(
+#                greps '-o' "$pattern" "$file" |
+#                    head -n 1 |
+#                    sed -e "s/## ${cmd}: //g" -e "s/ ##.*//g"
+#            )
+#            reply[$cmd]="${description:-''}"
+#        done
+#        # Print command completion
+#        for k v in ${(kv)reply}; do
+#            printf '\t%s:"%s"\n' "$k" "$v" | colrm
+#        done
+#    }
     
     
     
@@ -175,12 +192,16 @@ function fn() (
     function fn_completion() {
         # Completion for flags and options
         function completion_arguments() {
+            typeset file=$1
+            typeset -A reply
             typeset grep_pattern='^[ ]*##[ ]*-[^ ]+: .* ##[ ]*$'
             typeset sed_pattern='s/## ([-].*): (.*) ##/\1: \2/p'
-            typeset -A reply
             reply=("${(@f)$(grep -E $grep_pattern $zfunc/fn |
                 sed -n -E $sed_pattern |
-                awk -F ': ' '{print $1; print $2;}' )}")
+                awk -F ': ' '{print $1; print $2;}' )}") 2>/dev/null
+            if [[ $? -ne 0 ]]; then
+                error -1 'Parse error'
+            fi
             # Print completion for arguments
             local k v
             for k v in ${(kv)reply}; do
@@ -190,12 +211,14 @@ function fn() (
                 printf '\t%s"[%s]" \\\\\n' "$k" "$v"
             done
         }
+        
         # Completion for commands
         function completion_commands() {
-            typeset -A reply
             typeset file=$1
+            typeset -A reply
             typeset -a fn_commands=($(fn -p ${file:t} commands ${file:t}))
             # Parse commands
+            local cmd
             for cmd in $fn_commands; do
                 local pattern="## ${cmd}: .+ ##.*function ${fn_name}[\-\_]${cmd}[\s]*\(\)"
                 local description=$(
@@ -206,16 +229,18 @@ function fn() (
                 reply[$cmd]="${description:-''}"
             done
             # Print command completion
+            local k v
             for k v in ${(kv)reply}; do
                 printf '\t%s:"%s"\n' "$k" "$v" | colrm
             done
+            return 0
         }
         # Find files starting with the specified 'fn_name'
         typeset -a cmd_completion=()
         typeset -a arg_completion=()
         # Parse each file and generate argument/command completion
-        typeset fn_dir file cmd
-        fn_dir="${$( fn src $fn_name ):h}"
+        typeset fn_dir file
+        fn_dir="${$(fn src $fn_name):h}"
         for file in ${fn_dir}/${fn_name}*; do
             autoload +X ${file:t}
             arg_completion=(${(@f)"$(completion_arguments $file)"})
diff --git a/zsh/site-functions/get-arguments b/zsh/site-functions/get-arguments
--- a/zsh/site-functions/get-arguments
+++ b/zsh/site-functions/get-arguments
@@ -25,13 +25,16 @@
 #       typeset -A myArray
 #       get-arguments -A myArray -f A,B -o C,D -- -C opt-C -A -D opt-D -B
 function get-arguments() {
-    typeset -a name_list
-    typeset -i distance
-    
+    # Load 'zsh/zutil' module
+    if ! zmodload zsh/zutil; then
+        error -127 'Cannot load module'
+    fi
     
     #MARK: - Parse Argument Names
     # Parse list of argument names and calculate
     # shift distance
+    typeset -a name_list
+    typeset -i distance
     function get-arguments-parse-list() {
         distance=0
         # Type (flag or option)
@@ -147,11 +150,10 @@ function get-arguments() {
     if [[ $? -ne 0 ]]; then
         error -1 'Failed to parse options.'
     fi
-#    if [[ $1 =~ '^[-]{1,2}$' ]]; then
-    if [[ $1 == '--' ]]; then 
+    if [[ $1 == '--' ]]; then
         shift
     fi
-    trap "builtin set -- ${argv}" EXIT
+    trap "builtin set -- \"${argv}\"" EXIT
     
     # Append each flag to 'opts' as an option
     # with value 'flag is set'
