[CS942-0708] 41 files changed, 985 insertions(+), 782 deletions(-).
Signed-off-by: Maxim Puchkov <maxim_puchkov@sfu.ca>

diff --git a/zsh/functions/fn b/zsh/functions/fn
--- a/zsh/functions/fn
+++ b/zsh/functions/fn
@@ -16,6 +16,8 @@
 ## arg1: vars ##
 ## arg2: ##
 function fn() {(
+    autoload -Uz print-line
+    
     ## def: print function source code ##
     function fn_def() {
         local label="function %U%B${fn_name}%b%u () {"
@@ -40,7 +42,6 @@ function fn() {(
     ## show: display function definition and source file ##
     function fn_show() {
         local fn_code=$(fn def $fn_name)
-        local fn_file=$(fn_src $fn_name)
         local fn_line=${(%):-"%F{8}${(l:$COLUMNS::-:)}%f"}
         builtin print -f '%s\n%s\n%s\n\n%s\n' \
             "$fn_line" "$fn_code" "$fn_line" "${(D)fn_file}"
@@ -48,7 +49,6 @@ function fn() {(
     }
     ## open: open function source file ##
     function fn_open() {
-        local fn_file=$(fn_src $fn_name 2>/dev/null)
         if [[ ! -r $fn_file ]]; then
             error -1 'Cannot read source file for function $fn_name.'
         fi
@@ -64,22 +64,28 @@ function fn() {(
     }
     ## sub: list functions defined within a function ##
     function fn_sub() {
-        if ! fn_file=$(fn_src $fn_name); then
-            return 1
-        fi
         typeset fn_syntax fn_pattern
-        fn_syntax="${fn_prefix}_((?:\w|-)+)"
+        fn_syntax='function ('${fn_prefix}'|\$0|\$\{(\(.*\))?0\})_((?:\w|-)+)'
         fn_pattern="^[^#]*(function\s+${fn_syntax}|${fn_syntax}\s*\(\))\s*"
+        
         typeset -a list
         list=($( egrep -o -i -E "${fn_pattern}" -- $fn_file ))
         list=(${${list#'function'*}%*'()'})
+        
+        typeset -a result
         local f
         for f in $list; do
             typeset subfn_name=${f%'('*')'}
+            subfn_name=$(sed -E -e 's/\$(\{0\}|0)/'${fn_prefix}'/g' <<< $subfn_name)
             if [[ ${+functions[$subfn_name]} ]]; then
-                printf '%s\n' "$subfn_name"
+                result+=($subfn_name)
             fi
         done
+        if [[ -z $result ]]; then
+            error -2 'BOB'
+            return 1
+        fi
+        print -l -- $result
         return 0
     }
     ## commands: list function commands ##
@@ -105,9 +111,6 @@ function fn() {(
     }
     ## options: list function flags and options ##
     function fn_options() {
-        if ! fn_file=$(fn_src $fn_name); then
-            return 1
-        fi
         typeset grep_pattern='^[ ]*##[ ]*[\-\+][^ ]+: .* ##[ ]*$'
         typeset sed_pattern='s/## ([\-\+].*): (.*) ##/\1: \2/p'
         typeset -A reply
@@ -126,9 +129,6 @@ function fn() {(
     
     # Completion for flags and options
     function fn_completion-arguments() {
-        if ! fn_file=$(fn_src $fn_name); then
-            return 1
-        fi
         typeset -A reply
         typeset grep_pattern='^[ ]*##[ ]* (.+) [-+][^ ]+[^:]*: .* ##[ ]*$'
         typeset sed_pattern='s/## (.+) ([-+][^ ]+)[^:]*: (.+) ##/\2: \3/p'
@@ -152,10 +152,6 @@ function fn() {(
     
     # Completion for commands
     function fn_completion-commands() {
-        typeset fn_file
-        if ! fn_file=$(fn_src $fn_name); then
-            return 1
-        fi
         typeset -A reply
         typeset -a fn_commands=($(fn commands ${fn_file:t}))
         # Parse commands
@@ -283,30 +279,26 @@ EOF
         return 0
     }
     
-    function fn_t() {
-        typeset -ft $fn_name
-        $fn_name 
-    }
+    ## d: debug function ##
+    function fn_d() {(
+        typeset -fT $fn_name
+        print-line
+        $fn_name $argv
+        print-line
+    )}
     
-    function fn_edit() {
-        local fn_file=$(fn_src $fn_name 2>/dev/null)
-        if [[ ! -r $fn_file ]]; then
-            error -1 'Cannot read source file for function $fn_name.'
-        fi
+    function fn_edit() {(
         ${=EDITOR} -- $fn_file
         return 0
-    }
-    function fn_xedit() {
-        local fn_file=$(fn_src $fn_name 2>/dev/null)
-        if [[ ! -r $fn_file ]]; then
-            error -1 'Cannot read source file for function $fn_name.'
-        fi
+    )}
+    function fn_xedit() {(
         /usr/bin/open -F -a Xcode -- $fn_file
         return 0
-    }
-    function fn_x() {
-        funct
-    }
+    )}
+    
+    function fn_modify() {(
+        cat <$fn_file
+    )}
     
     
     
@@ -319,10 +311,9 @@ EOF
                   -- $argv
     # Set compgen overwrite response (-y)
     typeset response=${optlist[-y]:+'yes'}
-    
     # Show help message (-h)
-    if [[ $optlist[-h] -eq 1 ]] ||
-       [[ $# -eq 0 ]]; then
+    if [[ $# -eq 0 ]] ||
+       [[ $optlist[-h] -eq 1 ]]; then
         $0 print-commands $0
         return 0
     fi
@@ -333,53 +324,35 @@ EOF
     # Command name
     typeset cmd=$1
     if [[ ${+functions[${0}_${cmd}]} -ne 1 ]]; then
-        error -127 'Unknown command: $cmd.'
+        error -127 'Command not found: ${cmd}.'
     fi
     shift
-    # Command argument
-    typeset fn_name="${argv}"
-    if [[ $# -eq 0 ]]; then
-        error -1 'Missing command argument: function name.'
+    
+    # Command arguments
+    typeset fn_name=$1
+    if [[ -z $fn_name ]]; then
+        error -1 'Missing function name.'
     fi
+    shift
     # Return if function is not defined
-    if [[ ${+functions[$fn_name]} -eq 0 ]]; then
-        error -1 "Function '\$fn_name' is not defined."
+    if [[ ${+functions[$fn_name]} -ne 1 ]]; then
+        error -127 'Function not found: ${fn_name}.'
     fi
     
+    
+    # Function name prefix
+    if [[ -z $fn_prefix ]]; then
+        typeset fn_prefix=${fn_name%%[_-]*}
+    fi
     
     # Source file
-    typeset fn_file
-    # Function name prefix
-    if [[ ! -v fn_prefix ]]; then
-        export fn_prefix=${fn_name%%[_-]*}
-    fi
-    
-    
-    
-    
-#    # Check argument count
-#    case $# in
-#        0)  warning 'Command needs arguments.'
-#            $0 print-commands $0
-#            return 2 ;;
-#        1)  error -2 'Function name is not specified.'
-#            return 2 ;;
-#    esac
-    
-    
-    if [[ $cmd == 'isdef' ]]; then
-        ${0}_${cmd} $fn_name
-        return $?
-    fi
-
-    # Execute the command
     autoload +X $fn_name
-    ${0}_${cmd} $fn_name
-    local -i cmd_status=$?
-    if [[ $cmd_status -ne 0 ]]; then
-        error -$cmd_status -c -- \
-            '\$cmd: command failed to complete (error code \${cmd_status}).'
+    typeset fn_file=$functions_source[$fn_name]
+    if [[ -z $fn_file ]]; then
+        error -1 'Cannot read source file for function ${fn_name}.'
     fi
     
-    return 0
+    # Execute the command
+    ${0}_${cmd} $fn_name $argv
+    return $?
 )}
diff --git a/zsh/site-functions/get b/zsh/site-functions/get
--- a/zsh/site-functions/get
+++ b/zsh/site-functions/get
@@ -9,133 +9,233 @@
 
 # Name:   get
 # Usage:  get [-A array] [-f flag [...]]
-#             [-o option[:default] [...]] -- argv
+#             [-o option[:default_value] [...]] -- argv
 emulate -L zsh
+# Print usage
+if [[ $# -eq 0 ]]; then
+  usage 'No input' \
+    "${0} -f flag -o opt -- -flag -opt optval"
+  return 2
+fi
+# Load required zsh builtin commands
+if ! zmodload -F zsh/zutil b:zparseopts &>/dev/null; then
+  error -1 'Unable to load zsh module'
+  return 1
+fi
 
 
-# Load 'zformat' and 'zparseopts' zsh builtin commands
-if ! zmodload -F zsh/zutil -b:zformat b:zparseopts &>/dev/null; then
-    error -1 'Unable to load zsh module'
-    return 1
+
+#MARK: - Functions
+typeset -x CALLER=$(caller)
+if [[ $CALLER == $SHELL ]]; then
+  # Log recognized option names and values
+  function get_wlog() {
+    if [[ $1 == '-T' ]]; then
+      builtin print -Pn -- '$$ [%D %*]\t'
+      shift
+    fi
+    /usr/bin/sed -E \
+      -e 's/<([^>]+)>/<'$(esc 33 -t '\1' -r 0)'>/g' \
+      < <(print -- $argv) \
+      >&2
+    return 0
+  }
+else
+  typeset -f get_wlog() return 0
 fi
 
 
 # Split array in two arrays 'left_split' and 'right_split' at
-# next occurrence of str:
+# next occurrence of 'str':
 #   array(1..n)  ~>  left_split(1..i), right_split(i+1,n)
 function get_split_arrays() {
-    if [[ $# -eq 0 ]]; then
-        usage 'No input.' "$0 str [values,]" "$0 -- a1 a2 -- b1 b2"
-        pcre_compile -L
-        return 2
-    fi
-    typeset str="$1"
-    shift
-    typeset -i index=${argv[(i)${~str}]}
-    typeset -ag left_split right_split
-    left_split=(${argv[1,$index]})
-    right_split=(${argv[$index+1,#]})
-    return 0
+  [[ $# -eq 0 ]] && error -1 'No input.'
+  local str="$1"
+  shift
+  # Get position of the string in 'argv'
+  local -i index=${argv[(i)${~str}]}
+  typeset -ag left_split right_split
+  left_split=(${argv[1,$index]})
+  right_split=(${argv[$index+1,#]})
+  return 0
 }
-
-
-#MARK: - get
-# Options of 'get' (all arguments up to '--')
-function get_names() {
-    # Find arguments with prefix '-' ('-f', '-o', etc.)
-    typeset -a matches=(${(M)argv:#-*})
-    if [[ -z $matches ]]; then
-        error -1 'Unknown option descriptions.'
-    fi
-    
-    # For each option, determine indices of its
-    # first and last arguments
-    typeset -aU opt_args
-    typeset -i i max_index
-    let max_index=$#matches-1
-    for i in {1..$max_index}; do
-        # Current and next options of 'get'
-        current=$matches[$i]
-        next=$matches[$i+1]
-        # Select all arguments in-between current
-        # and next option in 'argv'
-        let begin=$argv[(wi)$current]
-        let end=${argv[(wi)$next]}
-        opt_args=($argv[$begin+1,$end-1])
-        # Pass arguments to current option
-        case $current in
-            -f) flag_names+=($opt_args) ;;
-            -o) opt_names+=($opt_args)  ;;
-            -A) reply=$opt_args[1]      ;;
-        esac
-        shift $#opt_args
-    done
-    return 0
-}
-
-
-#MARK: - zparseopts
-# Options of 'zparseopts' (all arguments after '--')
-function get_values() {
-  # Recognized flags/options
-  typeset -a flags
-  typeset -A opts
-  flags=()
-  opts=()
-  # Set 'specs' for the 'zparseopts' builtin
-  typeset -a specs
-  specs=(${^flag_names}'=flags' ${^option_names}':=opts')
-  # Parse parameters
-  if ! builtin zparseopts -D -E -- $specs &>/dev/null; then
-    error -$? -c +A 'zparseopts failed to parse option specs.'
-  fi
-  return $?
-}
-
 
 # Split positional arguments at '--'
 typeset delim='--'
 if [[ $argv[(wi)$delim] -gt $# ]]; then
-    error -1 'Delimiter ${delim} was not found.'
+  error -1 'Delimiter ${delim} was not found.'
 fi
 get_split_arrays $delim $argv
 options_desc=($left_split)
 options_spec=($right_split)
 
+get_wlog "Splitting argv=<$argv> at delim=<$delim>"
+get_wlog "Left Split=<$left_split>; Right Split=<$right_split>"
 
-# Declare output array
-typeset reply
-if [[ -z $reply ]]; then
-    reply='reply'
-fi
-typeset -Ag $reply
+
+
+
+
+#MARK: - get
+# Options of 'get' (all arguments up to '--')
+function get_names() {
+  # Find arguments with prefix '-' ('-f', '-o', etc.)
+  typeset -a matches=(${(M)argv:#--*})
+  if [[ -z $matches ]]; then
+    error -1 'Bad option names.'
+  fi
+  
+  typeset -aU opt_args
+  local arg default_value
+  # Find names in 'argv' starting with a '-'
+  # and select all arguments between them
+  local -i max_index i
+  let max_index=${#matches}-1
+  for i in {1..$max_index}; do
+    # Current and next options of 'get'
+    current=${matches[$i]}
+    next=${matches[$(( $i + 1 ))]}
+    # Select arguments from 'argv' for current option
+    #   --flags [begin..end] --opts [begin..end]
+    let begin=${argv[(wi)$current]}+1
+    let end=${argv[(wi)$next]}-1
+    opt_args=(${argv[$begin,$end]})
+    
+    #
+    for arg in $opt_args; do
+      name="${arg%%,*}"
+      # Default value
+      if [[ $arg =~ '.:=.' ]]; then
+        value=${arg##*:=}
+        opt_args[(i)$arg]=${arg%:=*}
+        arg=${arg%:=*}
+        default_values+=( [$name]="$value" )
+      fi
+      # Alias names
+      if [[ $arg =~ '.,.' ]]; then
+        name_aliases="${arg#*,}"
+        greenbg $name $name_aliases
+        alias_names+=([$name]=${name_aliases})
+      fi
+    done
+
+    # Pass arguments to current option
+    case $current in
+      (--F|--flags)
+        flag_names+=($opt_args)
+      ;;
+      (--O|--options)
+        opt_names+=($opt_args)
+      ;;
+      (--A)
+        reply_array_id=${opt_args[1]}
+      ;;
+      (--*)
+        warning 'Bad option ${current}.'
+      ;;
+    esac
+  done
+  
+  get_wlog "Output array identifier is <${reply_array_id}>."
+  get_wlog "Flag names are <${flag_names}>."
+  get_wlog "Option names are <${opt_names}>."
+  get_wlog "Option default values are <${(kv)default_values}>."
+  get_wlog "Alias names are <${(kv)alias_names}>."
+  return $?
+}
 
 
 # Get names of flags and options
+typeset reply_array_id='reply'
 typeset -aU flag_names opt_names
 flag_names=()
 opt_names=()
 get_names $options_desc
-
 # Exit if no flag or option names were recognized
 if [[ -z $flag_names ]] &&
    [[ -z $opt_names ]]; then
-    error -1 'Missing descriptions of flags and/or options.'
+  error -1 'Missing option descriptions.'
 fi
 
 
+
+
+
+#MARK: - zparseopts
+# Options of 'zparseopts' (all arguments after '--')
+function get_values() {
+  # Set 'specs' for the 'zparseopts' builtin
+  local -a specs
+  specs=(${^flag_names}'=flags' ${^opt_names}':=opts')
+  # Parse parameters
+  builtin zparseopts -D -E -K -M -- $specs &>/dev/null
+  if [[ $? -ne 0 ]]; then
+    error -1 +A 'zparseopts failed to parse option specs.'
+  fi
+  if [[ ${argv[-1]} == '--' ]]; then
+    shift -p
+  fi
+  set -A rest $argv
+  return 0
+}
+
+
 # Parse and store recognized option values in an array
-get_values $options_names
+# Recognized flags/options
+typeset -A alias_names;     alias_names=()
+typeset -A default_values;  default_values=()
+typeset -ag flags;          flags=()
+typeset -Ag opts;           opts=()
+typeset -a rest;            rest=()
+get_values $options_spec
+
+
+# Initialize output array
+# Recognized options and options with default values
+typeset -a {opts,def}_keys
+opts_keys=(${(k)opts})
+def_keys=(${(Mk)defaults:#--*})
+# Non-recognized flags/options
+typeset -a unset_{flags,opts}
+unset_opts=(${${:-'-'${^opt_names}}:|opts_keys})
+unset_flags=(${${:-'-'${^flag_names}}:|flags})
+# Set remaining arguments of the caller
+trap '{ set -- '${(q)rest}'; [[ $1 == "--" ]] && shift; }' EXIT
 
 
 
-echo;echo;echo
-print-var argv
 
 
-(red "'get' args: $options_desc")>&2
-(blue "'zparseopts' args: $options_spec")>&2
-print -- "  >>> $flag_names ++ $opt_names" >&2
+#MARK: - Result Array
+# Initialize the result array
+typeset -A result
+result=()
+# Append recognized flags as (name, 1) pairs
+for name in $flags; do
+  result+=( [$name]=1 )
+done
+# Append recognized options as (name, value) pairs
+for name value in ${(kv)opts}; do
+  result+=( [$name]=$value )
+done
+
+
+# If an option is not set but has a default value,
+# set option to its default value
+#local {default,given}_value
+#for name in $def_keys; do
+#  default_value=${defaults[(k)$name]}
+#  given_value=${result[(k)$name]}
+#  if [[ -n $default_value ]] &&
+#     [[ -z $given_value ]]; then
+#      result+=( [$name]=$default_value )
+#  fi
+#done
+
+# Set the output associative array to the
+# (name, value) pairs of result array
+typeset -Ag $reply_array_id
+set -A ${reply_array_id} ${(kv)result}
 
 return 0
 
@@ -253,7 +353,7 @@ return 0
 #        ( name='zparseopts' \
 #            error -$parse_status -c "Invalid '%U\${name}%u' specs: {\${specs}}." )
 #    fi
-#
+
 #    # Recognized options and options with default values
 #    typeset -a {opts,def}_keys
 #    opts_keys=(${(k)opts})
