[CS927-0530] 14 files changed, 271 insertions(+), 149 deletions(-).
Signed-off-by: Maxim Puchkov <maxim_puchkov@sfu.ca>

diff --git a/zsh/functions/fn b/zsh/functions/fn
--- a/zsh/functions/fn
+++ b/zsh/functions/fn
@@ -14,7 +14,7 @@ function fn() (
         local fdef=$( functions $fname )
         local highlight=(pygmentize -f 'terminal16m' -O style='xcodedark' -l 'zsh')
         if [[ -z ${commands[pygmentize]} ]]; then
-            error 'Cannot find pygments.'
+            error -0 'Cannot find pygments.'
             highlight='cat'
         fi
         printf '%s\n' "$fdef" | $highlight
@@ -23,7 +23,7 @@ function fn() (
     function fn_src() {
         local fsource=$functions_source[$fname]
         if [[ -z $fsource ]]; then
-            error "Definition file not found: '$(Bad $fname)'."
+            error "Definition file not found: %F{1}$fname%f."
             return 1
         fi
         echo "$fsource"
@@ -67,7 +67,6 @@ function fn() (
     ## print-commands: format and list function commands ##
     function fn_print-commands() {
         name_prefix="${name_prefix:-${fname%%_*}}"
-#        print -P    '%B%UCommands%u%b:'
         print_h1 'Commands:'
         print -P -l "%F{14}$( fn -p $name_prefix commands $fname )%f"
         return 0
@@ -92,14 +91,15 @@ function fn() (
     case $# in
         0) fn print-commands $0
            return 2 ;;
-        1) error 'Function name is not specified.'
+        1) error '?/ Function name is not specified.'
            return 2 ;;
     esac
 
     # Function command
     typeset cmd=$1
     shift
-    if ! ( functions | grep -w -e "fn_$cmd" &>/dev/null ); then
+#    if ! ( functions | grep -w -e "fn[-_]$cmd" &>/dev/null ); then
+    if ! ( whence -
         error "Unknown command: %F{1}$cmd%f."
         return 127
     fi
diff --git a/zsh/functions/template b/zsh/functions/template
--- a/zsh/functions/template
+++ b/zsh/functions/template
@@ -58,26 +58,26 @@ function template() {
     # Copy template file to the target directory and
     # replace macro strings.
     function copy_template() {
-        # If test run is enabled, then only
-        # print the filenames of
-        typeset test_run=${optlist[t]}
-        if [[ -n $test_run ]]; then
+        # Test run: print the names of the files only
+        if [[ -n ${optlist[t]} ]]; then
             print -P -- "TestRun $0 [$$]: "\
                         "orig[$template_orig] --> "\
                         "New[%F{2}$template_new%f]."
             return 0
         fi
         
-        # Copy the original template file.
+        # Copy the original template file to new location
         if ! ( cp -n $template_orig $template_new ); then
             error 'Fatal error.'
             return 1
         fi
-        # Substitute template macro strings.
+        # Substitute all template macro strings in the file
         substitute_macros "$template_new" $TEMPLATE_MACROS
-        print -P -- "Generated template file: %F{2}$template_new%f."
-        print -P -- ""
-        echo $m_template_id > $savefile
+        print -P -- "Generated template file: %F{2}$template_new%f (ID: $m_template_id)."
+        
+        # Update 'template.seq' and 'template.id' files
+        echo $template_new   >> $template_seq_file
+        echo $m_template_id  > $template_id_file
         return 0
     }
     
@@ -89,7 +89,7 @@ function template() {
         m_filename=$name
         m_package_name='zsh'
         template_new="${target_dir}/${name}"
-        template_orig="$TEMPLATES_DIR/$0"
+        template_orig="$templates_dir/$0"
         
         copy_template
     }
@@ -101,7 +101,7 @@ function template() {
         m_filename=$name
         m_package_name='Z-Function'
         template_new="${target_dir}/${name}"
-        template_orig="$TEMPLATES_DIR/$0"
+        template_orig="$templates_dir/$0"
         
         copy_template
     }
@@ -112,7 +112,7 @@ function template() {
 #        name="${$( generate_filename $1 ):-${(U)0}}"
 #        local package='Z-Function'
 #        template_new="${target_dir}/${name}"
-#        template_orig="$TEMPLATES_DIR/$0"
+#        template_orig="$templates_dir/$0"
 #        
 #        copy_template
 #    }
@@ -124,7 +124,7 @@ function template() {
         m_filename=$name
         m_package_name='Python'
         template_new="${target_dir}/${name}"
-        template_orig="$TEMPLATES_DIR/$0.py"
+        template_orig="$templates_dir/$0.py"
         m_shebang='#!\/usr\/bin\/env\ python3'
         if (copy_template); then
             chmod a+x $template_new
@@ -152,7 +152,7 @@ function template() {
         m_filename=$name
         m_package_name='Terminal'
         template_new="${target_dir}/${name}"
-        template_orig="$TEMPLATES_DIR/$0"
+        template_orig="$templates_dir/$0"
         if (copy_template); then
             chmod a+x $template_new
         fi
@@ -166,7 +166,7 @@ function template() {
         m_filename=$name
         m_package_name='Services'
         template_new="${target_dir}/${name}"
-        template_orig="$TEMPLATES_DIR/$0"
+        template_orig="$templates_dir/$0"
         copy_template
         
         template -d $ZTERM/Services ztool $1
@@ -176,28 +176,20 @@ function template() {
     
     
     
+    
     if [[ $# -eq 0 ]]; then
-        fn print-commands 'template'
+        fn print-commands $0
         return 2
     fi
     
-    local savefile="$zterm/etc/template.id"
-    local lastid=0
-#    read_array lastid $savefile &>/dev/null
-    lastid=$(< $savefile)
+    # Files
+    typeset template_seq_file="$ZTERM/etc/template.seq"
+    typeset template_id_file="$ZTERM/etc/template.id"
+    touch $template_seq_file $template_id_file
+    typeset lastid=${$(< $template_id_file):-0}
+    typeset templates_dir="$ZDOTDIR/templates"
     
-    function getid() {
-        lastid=${${optlist[t]:+test-id$$}:-$(< $TEMPLATE_ID)}
-    }
-    function setid() {
-        
-    }
-    
-    # Template macro strings.
-    typeset -a TEMPLATE_MACROS=(
-        m_shebang   m_template_ts  m_filename   m_package_name     m_owner
-        m_username  m_date_full    m_date_year  m_organization_id  m_template_id
-    )
+    # Template macro strings
     local m_shebang   m_template_ts  m_filename   m_package_name     m_owner \
           m_username  m_date_full    m_date_year  m_organization_id  m_template_id
     m_shebang='#!\/bin\/zsh'
@@ -210,46 +202,38 @@ function template() {
     m_date_year=$( date +'%Y' )
     m_organization_id='com.maximpuchkov'
     m_template_id=( $(( $lastid + 1 )) )
+    export TEMPLATE_MACROS=(
+        m_shebang   m_template_ts  m_filename   m_package_name     m_owner
+        m_username  m_date_full    m_date_year  m_organization_id  m_template_id
+    )
     
-    export TEMPLATE_MACROS
-    export TEMPLATES_DIR="$ZDOTDIR/templates"
+    typeset name  target_dir
+    typeset template_orig  template_new
     
-    # Function options.
+    # Function options
     typeset -A optlist
     get_options optlist 'd:Dt' "$@"
     shift $optlist[length]
     
-    # Source and compound commands.
-    local src cmd
-    src=$( basename $0 )
-    cmd=$1
-    
-    local name template_new template_orig target_dir
-    
-    # Template output directory (-d).
+    # Template output directory (-d)
     target_dir=${optlist[d]:a}
     if [[ -n "$target_dir" ]] && [[ ! -d "$target_dir" ]]; then
-        error "Invalid directory: '$target_dir'"
+        error "Invalid directory: %F{1}$target_dir%f."
         return 2
     fi
-    if [[ $optlist[t] ]]; then
-        m_template_id='No ID'
+    # Test run (-t)
+    if [[ -n $optlist[t] ]]; then
+        m_template_id='No identifier'
     fi
     
-    # Compound command.
-    case $cmd in
-        "")
-            print "Usage:"
-            print -x2 "\t$(b_bcyan $src) $(cyan 'command') $(cyan 'arguments')... - call command '$src command' with a list of 'arguments'."
-            ;;
-        *)
-            shift
-            ${src}_${cmd} "$@"
-            local ecode=$?
-            if [ $ecode = 127 ]; then
-                echo "Unknown command: $(Bad $cmd) (Exit code $ecode)." >&2
-            fi
-            ;;
-    esac
-    return $ecode
+    # Subcommand
+    typeset cmd=$1
+    shift
+    if ! (whence ${0}_${cmd}); then
+        error "Function command not found: %F{1}$cmd%f."
+        return 127
+    fi
+    
+    ${0}_${cmd} "$@"
+    return $?
 }
diff --git a/zsh/site-functions/error b/zsh/site-functions/error
--- a/zsh/site-functions/error
+++ b/zsh/site-functions/error
@@ -7,33 +7,94 @@
 #  Copyright © 2020 Maxim Puchkov. All rights reserved.
 
 
-# Raise runtime error:
-#   error description
+# Print an error/warning and its description.
+#   * Error - the caller will terminate at an error
+#     and return the error code (default code: 1).
+#       error -1   'Fatal error'
+#       error -127 'Command not found'
+#
+#   * Warning - the caller will not terminate at a warning
+#     and continue without returning any value.
+#       warning  'description...'
+#       error -0 'description...'
 function error() {
-    # Error exit code.
-    typeset -i10 exit_code=1
-    if [[ $1 =~ '-[0-9]+' ]]; then
-        exit_code=${1#-}
-        shift
-    fi
+#    trap 'echo ${0}-*' EXIT
+#    echo "${0}-*"
     
-    # Return after this function exits.
-    trap "return $exit_code" EXIT
-    
-    # Error title and description.
-    typeset error_title error_desc
-    error_title="%F{9}Error%f."
-    error_desc="${(j:\n       :)@:-no message.}"
-    
+    # MARK: - Functions
     # Capitalize first letter of the description
-    # and add a trailing period.
-    error_desc="${(C)error_desc[1]}${${error_desc:1}}"
-    if  [[ ! "${(q)error_desc}" =~ '\n' ]] &&
-        [[ ! "${(q)error_desc}" =~ '^.*\.$' ]]; then
-        error_desc="${error_desc}."
-    fi
+    # and add a trailing period
+    function error-format-description() {
+        message_desc="${message_desc:-No description.}"
+        message_desc="${(C)message_desc[1]}${${message_desc:1}}"
+        if [[ ! "${(q)message_desc}" =~ '\n' ]] &&
+           [[ ! "${(q)message_desc}" =~ '^.*\.$' ]]; then
+            message_desc="${message_desc}."
+        fi
+    }
+    __XXX__PATTERN='[0=9]
+    # Parse function options
+    function error-parse-options() {
+        set -- $@
+        while [[ $1 =~ '^-' ]] &&
+              [[ $1 != '--' ]]; do
+            case $1 in
+                # Display the exit code for errors
+                -p|--print-code)
+                    exit_code_label=" %F{7}[$exit_code]%f"
+                ;;
+                # Do not format description
+                -n|--no-format)
+                    unfunction error-format-description
+                    function error-format-description() {
+                        return 0
+                    }
+                ;;
+                # Silence output
+                -0|--null)
+                    output_device=/dev/null
+                ;;
+                # Set the error return code
+                *)  if [[ $1 =~ '-[0-9]+' ]]; then
+                        exit_code=${1#-}
+                    else
+                        break
+                    fi
+                ;;
+                -<0-255>)
+                    
+                *)  break
+                ;;
+            esac
+            shift
+        done
+    }
     
-    # Print error and return.
-    print -P "$error_title $error_desc" >&2
-    return $exit_code
+    
+    #MARK: - Data
+    # Exit code
+    typeset -i exit_code=1
+    typeset exit_code_label=''
+    # Output
+    typeset output_device=/dev/stderr
+    
+    error-parse-options
+    
+    # Title text
+    typeset message_title
+    if [[ $exit_code -gt 0 ]]; then
+        trap "return $exit_code" EXIT
+        message_title="%F{1}Error%f"
+    else
+        message_title="%F{3}Warning%f"
+    fi
+    # Description text
+    typeset message_desc="${(j:\n       :)@}"
+    error-format-description
+    
+    # Print the error/warning message to stderr
+    print -P -- "%U$message_title%u$exit_code_label: $message_desc" >&2
+    
+    unfunction -m "${0}-*"
+    return 0
 }
