[CS936-0617] 19 files changed, 421 insertions(+), 328 deletions(-).
Signed-off-by: Maxim Puchkov <maxim_puchkov@sfu.ca>

diff --git a/zsh/functions/hx b/zsh/functions/hx
--- a/zsh/functions/hx
+++ b/zsh/functions/hx
@@ -7,44 +7,58 @@
 #  Copyright © 2020 Maxim Puchkov. All rights reserved.
 
 
-# Hexdump files.
 function hx() {
-   function __hx_dump() {
-        local filepath="$1"
-        printf "  $(bold %s)\n" "${filepath:t}"
-        if ( ! hexyl -- "$filepath" ); then
-            return 1
-        fi
-        return 0
-    }
-    
-    local n_files=$#
-    local exitcode=0
-    case $n_files in
-        0)  #error 'No input files'
-            #exitcode=2
-            hexyl < /dev/stdin
-        ;;
-        1)  __hx_dump "$1"
-            exitcode=$?
-        ;;
-        *)  local i
-            for i in {1..$n_files}; do
-                local file=${@[$i]}
-                if [[ $i -gt 1 ]]; then
-                    print-line
-                fi
-                printf " $(lgrey '(%d/%d)')" $i $n_files
-                __hx_dump "$file"
-                exitcode=$(( $exitcode + $? ))
-            done
-            if [[ $exitcode -gt 0 ]]; then
-                echo 
-                error "$exitcode files not found."
-            fi
-        ;;
-    esac
-    
-    unfunction -m "__${0}_*"
-    return $exitcode
+    typeset -a optlist=()
+    while [[ $1 =~ '^[-]' ]]; do
+        case $1 in
+            --) shift; break  ;;
+            *)  optlist+=($1) ;;
+        esac
+        shift
+    done
+    S "hexyl $optlist <&0"
+    hexyl $optlist <&0
 }
+
+
+# Hexdump files.
+#function hx() {
+#   function __hx_dump() {
+#        local filepath="$1"
+#        printf "  $(bold %s)\n" "${filepath:t}"
+#        if ( ! hexyl -- "$filepath" ); then
+#            return 1
+#        fi
+#        return 0
+#    }
+#
+#    local n_files=$#
+#    local exitcode=0
+#    case $n_files in
+#        0)  #error 'No input files'
+#            #exitcode=2
+#            hexyl < /dev/stdin
+#        ;;
+#        1)  __hx_dump "$1"
+#            exitcode=$?
+#        ;;
+#        *)  local i
+#            for i in {1..$n_files}; do
+#                local file=${@[$i]}
+#                if [[ $i -gt 1 ]]; then
+#                    print-line
+#                fi
+#                printf " $(lgrey '(%d/%d)')" $i $n_files
+#                __hx_dump "$file"
+#                exitcode=$(( $exitcode + $? ))
+#            done
+#            if [[ $exitcode -gt 0 ]]; then
+#                echo
+#                error "$exitcode files not found."
+#            fi
+#        ;;
+#    esac
+#
+#    unfunction -m "__${0}_*"
+#    return $exitcode
+#}
