[CS933-0607] 29 files changed, 936 insertions(+), 385 deletions(-).
Signed-off-by: Maxim Puchkov <maxim_puchkov@sfu.ca>

diff --git a/Tools/semantic-history b/Tools/semantic-history
--- a/Tools/semantic-history
+++ b/Tools/semantic-history
@@ -6,23 +6,28 @@
 #  Created by Maxim Puchkov on 2020-04-17.
 #  Copyright © 2020 Maxim Puchkov. All rights reserved.
 
-##stat -f '%HT'
-#
-file="${1}"
-#
-#
-#if [[ ! -f $file ]]; then
-#    open $file
-#    return 0
-#fi
 
+# Path to file
+typeset file=$1
+() {
+    if [[ ! -r $1 ]] && [[ -r $2 ]]; then
+        file=$2
+    fi
+} ${file} ${file%.}
 
-regular_file="${file%.}"
-
-if [[ -r "$regular_file" ]] &&
-    [[ -f "$regular_file" ]]; then
-    open -a Xcode -g "$regular_file"
-    return 0
+# Open regular files in Xcode
+if [[ -f $file ]]; then
+    open -a Xcode $file
+else
+    open $file
 fi
 
-open "$file"
+# Check exit code
+typeset exit_code=$?
+if [[ $exit_code -ne 0 ]]; then
+    typeset title="Error ($exit_code)"
+    typeset subtitle="${0:t}"
+    typeset message="Cannot open '$file'"
+    zsh "$ZTERM/Tools/do-applescript" Notify $message $title $subtitle
+fi
+return 0
diff --git a/zsh/functions/cdp b/zsh/functions/cdp
--- a/zsh/functions/cdp
+++ b/zsh/functions/cdp
@@ -9,106 +9,95 @@
 
 # Change directory and print its path.
 function cdp() {
-    trap "unfunction -m '${0}_*'" EXIT
-    
+    #MARK: - Functions
+    trap "unfunction -m '${0}-*'" EXIT
     # Print error message
-    function cdp_error() (
-        typeset program_label error_text
-        program_label="%B%F{9}${program_name}%f%b"
-        error_text="$@"
-        print -P -- "${program_label}: ${error_text}"
-    ) >&2
+    function ${0}-error() {
+        typeset program_name=${0%%-*}
+        typeset code=1
+        if [[ $# -gt 1 ]]; then
+            code=$1
+            shift
+        fi
+        error -$code --title "$program_name" \
+              --no-autocapitalize --highlight "$@"
+        return $?
+    }
     
-    
-    # Program data
-    typeset program_name=$0
+        
+    #MARK: - Options
     typeset -A optlist
+    get-arguments -A optlist -f 'q,s,L,P' -- $argv
     
-    # Program options
-    optlist=()
-    while [[ $1 =~ '^-' ]]; do
-        case $1 in
-            -[qsLP])
-                optlist+=($1 'on')
-            ;;
-            -[0-9]*)
-                break
-            ;;
-            --)
-                shift
-                break
-            ;;
-        esac
-        shift
-    done
     
-    # Program arguments
-    typeset dir arg old new
+    #MARK: - Arguments
+    typeset dir arg
     case $# in
-        # No arguments: 'cd'
-        0)  dir="$HOME"
+        # No arguments (cd)
+        0)  dir=$HOME
         ;;
-        # One argument: 'cd DIR'
-        1)  arg="$1"
-            if [[ ${arg[1]} =~ '^(\+|\-)' ]]; then
-                local n stack_index
+        # One argument (cd DIR)
+        1)  arg=$1
+            if [[ $arg == '-' ]]; then
+                arg='-1'
+            fi
+            if [[ $arg =~ '^[-+][0-9]+' ]]; then
+                typeset stack_index
                 case ${arg[1]} in
-                    -)  n=${${arg:1}:-1}
-                        stack_index=$n
-                    ;;
-                    +)  n=${arg:1}
-                        stack_index=$(( ${#dirstack} - $n ))
-                    ;;
+                    -) stack_index=${arg:1}                        ;;
+                    +) stack_index=$(( ${#dirstack} - ${arg:1} ))  ;;
                 esac
-                dir="${dirstack[$stack_index]}"
-                if [[ -z "$dir" ]]; then
-                    cdp_error "no such entry in dir stack."
+                dir=${dirstack[$stack_index]}
+                if [[ -z $dir ]]; then
+                    cdp-error 1 'no such entry in dir stack.'
                     return 1
                 fi
             else
                 dir="${arg:a}"
             fi
         ;;
-        # Two arguments: 'cd OLD NEW'
-        2)  old="$1"
-            new="$2"
-            if [[ ! "$PWD" =~ "$old" ]]; then
-                cdp_error "string %F{1}$old%f is not in %F{1}$PWD%f."
+        # Two arguments (cd OLD NEW)
+        2)  typeset old new
+            old=$1
+            new=$2
+            if [[ ! $PWD =~ $old ]]; then
+                cdp-error 1 'string $old in not in $PWD.'
                 return 1
             fi
             dir="${PWD//$old/$new}"
         ;;
         # More than two arguments
-        *)  cdp_error 'too many arguments.'
+        *)  cdp-error 2 'too many arguments.'
             return 2
         ;;
     esac
     
     
+    #MARK: - Test Errors
     # Already in the directory
-    if [[ "$dir" == "$PWD" ]]; then
+    if [[ $dir == $PWD ]]; then
         return 0
     fi
     # Directory does not exist
-    if [[ ! -e "$dir" ]]; then
-        cdp_error "no such file or directory: %F{1}${dir:t}%f."
+    if [[ ! -e $dir ]]; then
+        cdp-error 1 'no such file or directory: $dir.'
         return 1
     fi
-    # File exists but not a directory
-    if [[ ! -d "$dir" ]]; then
-        cdp_error "%F{1}${dir:t}%f is not a directory."
+    # File exists but is not a directory
+    if [[ ! -d $dir ]]; then
+        cdp-error '$dir is not a directory.'
         return 1
     fi
     
     
-    #
-    builtin cd ${(k)=optlist} "$dir" 2>/dev/null
-    if [[ "$dir" != "$PWD" ]]; then
-        cdp_error "cannot change directory to %F{1}${dir:t}%f."
+    #MARK: - Change Directory
+    builtin cd ${(k)=optlist} $dir &>/dev/null
+    if [[ $? -ne 0 ]]; then
+        cdp-error 'cannot change directory to $dir.'
         return 1
     fi
     if [[ -z ${optlist[-q]} ]]; then
-        print -P "Directory changed to %F{2}$PWD%f."
+        print -P "Directory changed to %F{2}${PWD}%f."
     fi
     return 0
 }
diff --git a/zsh/functions/get-arguments b/zsh/functions/get-arguments
--- a/zsh/functions/get-arguments
+++ b/zsh/functions/get-arguments
@@ -7,99 +7,159 @@
 #  Copyright © 2020 Maxim Puchkov. All rights reserved.
 
 
-# <#Function description#>
+# Name:
+#   get-arguments
+#
+# Usage:
+#   get-arguments [-[Aa] array_id] [-[fo] name,...],... args
+#
+# Description:
+#   Parse arguments, store recognized flags
+#   and options in an array, and remove
+#   them from positional arguments.
+#
+# Examples:
+# 1. Parse options X,Y,Z and store their values in 'optlist':
+#       get-arguments -o X,Y,Z -- -Z opt-Z -X opt-x -Y opt-y
+# 2. Parse flags A,B, options C,D, and store result in 'myArray':
+#       typeset -A myArray
+#       get-arguments -A myArray -f A,B -o C,D -- -C opt-C -A -D opt-D -B
 function get-arguments() {
-    # Get short and long names
-    function get-argument-name() {
-        typeset str="$@"
-        typeset split_index=${str[(I)[,]]}
-        if [[ $split_index -eq 0 ]]; then
-            short_name=$str
-            long_name=''
-        else
-            short_name=${str[1,$(( $split_index - 1 ))]}
-            long_name=${str[$(( $split_index + 1 )),${#str}]}
-        fi
-    }
-    
-    # Set short and long option/flag name
-    function set-value() {
-        if [[ -n $short_name ]]; then
-            optlist[$short_name]="$@"
-        fi
-        if [[ -n $long_name ]]; then
-            optlist[$long_name]="$@"
-        fi
-    }
-    # Set option value
-    function set-option() {
-        set -- ${=optstring}
-        typeset index_short=${@[(I)-$short_name]}
-        typeset optval=''
-        if [[ $index_short -ne 0 ]]; then
-            optval=${@[(w)$(( $index_short + 1 ))]}
-            set-value $optval
-            shift_distance=$(( $shift_distance + 2 ))
-        else
-            typeset index_long=${@[(I)--$long_name]}
-            if [[ $index_long -ne 0 ]]; then
-                optval=${@[(w)$(( $index_long + 1 ))]}
-                set-value $optval
-                shift_distance=$(( $shift_distance + 2 ))
-            fi
-        fi
-    }
-    # Set flag value
-    function set-flag() {
-        set -- ${=optstring}
-        typeset index_short=${@[(I)-$short_name]}
-        typeset index_long=${@[(I)--$long_name]}
-        if [[ $index_short -ne 0 ]] ||
-           [[ $index_long -ne 0 ]]; then
-            set-value 'on'
-            shift_distance=$(( $shift_distance + 1 ))
-        fi
-    }
+    typeset -a name_list
+    typeset -i distance
     
     
-    optstring=${=@[-1]}
-    
-#    shift_distance=0
-#    trap "echo shift $shift_distance" EXIT
-    
-#    echo "Optstring= $optstring"
-#    last=${optstring[(Rw)-*]}
-    
-    
-    
-#    print -- $last
-#    i=${optstring[(wi)-*]}
-#    printf '%s' ${optstring[(w)$i]}
-    
-#    return 0
-
-    
-    set -- ${=@:1:-1}
-    
-    
-    typeset -Ag optlist
-    optlist=()
-    while [[ $1 =~ '^-' ]]; do
-        case $1 in
-            -o|--option)
-                get-argument-name $2
-                set-option
-                shift
-            ;;
-            -f|--flag)
-                get-argument-name $2
-                set-flag
-                shift
-            ;;
-            --) shift
-                break
-            ;;
-        esac
+    #MARK: - Parse Argument Names
+    # Parse list of argument names and calculate
+    # shift distance
+    function get-arguments-parse-list() {
+        distance=0
+        # Type (flag or option)
+        typeset name_type=$1
         shift
+        distance=$(( $distance + 1 ))
+        if [[ -z $1 ]]; then
+            error -1 'Cannot parse $name_type.'
+        fi
+        # List of individual names
+        name_list=()
+        if [[ $1 =~ '[,]' ]]; then
+            # Add each comma-separated
+            # argument to the list
+            while [[ $1 =~ '[,]' ]]; do
+                name_list+=($=1)
+                distance=$(( $distance + 1 ))
+                if [[   $1 =~ '[,][ ]?$' ]] &&
+                   [[ ! $2 =~ '[,]' ]]; then
+                    name_list+=($=2)
+                    distance=$(( $distance + 1 ))
+                    break
+                fi
+            shift
+            done
+        else
+            # If an argument does not contain commas,
+            # then it is the only argument
+            name_list+=($=1)
+            distance=$(( $distance + 1 ))
+        fi
+        return 0
+    }
+    
+    
+    #MARK: - Parameters for get-arguments
+    # Names of flags and options
+    typeset -aU flag_names option_names
+    flag_names=()
+    option_names=()
+    # Result array
+    typeset array_id array_type
+    array_id='optlist'
+    array_type='-A'
+    # Parse flag and option names
+    while [[ $1 =~ '^[-]' ]]; do
+        case $1 in
+            # Flags
+            -f|--flags)
+                # Parse flag names
+                get-arguments-parse-list $argv
+                if [[ $? -ne 0 ]]; then
+                    return 1
+                fi
+                # Append new flag names to 'flag_names' array
+                shift $distance
+                flag_names+=(${=${(s:,:)name_list}})
+            ;;
+            # Options
+            -o|--opts|--options)
+                # Parse option names
+                get-arguments-parse-list $argv
+                if [[ $? -ne 0 ]]; then
+                    return 1
+                fi
+                # Append new option names to 'option_names' array
+                shift $distance
+                option_names+=(${=${(s:,:)name_list}})
+            ;;
+            # Set name of the result associative array
+            -A) shift
+                array_id=$1
+                array_type='-A'
+                shift
+            ;;
+            # Set name of the result array
+            -a) shift
+                array_id=$1
+                array_type='-a'
+                shift
+            ;;
+            # Stop parsing parameters
+            --) shift ;&
+            *)  break ;;
+        esac
     done
+    # Check argument names
+    if [[ -z $flag_names ]] && [[ -z $option_names ]]; then
+        error -1 'Missing argument descriptions.'
+    fi
+    # Check that there are more arguments
+    if [[ $# -eq 0 ]]; then
+        #error -1 'Nothing to parse.'
+        return 1
+    fi
+    
+    
+    #MARK: - Parse Arguments with zparseopts
+    # Initialize 'flags' and 'opts' arrays
+    typeset -a flags
+    typeset -A opts
+    flags=()
+    opts=()
+    # Set 'specs' for the zparseopts builtin
+    typeset -a specs
+    specs=(${^flag_names}'=flags' ${^option_names}':=opts')
+    # Parse and store recognized flags and options
+    builtin zparseopts -D -E -- $=specs &>/dev/null
+    if [[ $? -ne 0 ]]; then
+        error -1 'Failed to parse options.'
+    fi
+    trap 'builtin set -- "'${argv}'"' EXIT
+#    trap "bluebg $argv; builtin set -- \"${argv}\";" EXIT
+    # Append each flag to 'opts' as an option
+    # with value 'flag is set'
+    typeset flag
+    for flag in $flags; do
+        opts[$flag]="${flag} is set"
+    done
+    
+    
+    #MARK: - Set Result Array
+    # Assign options to the result array
+    unset $array_id
+    typeset $=array_type -g $array_id
+    set -A $array_id ${(kv)opts}
+    
+    
+    unfunction -m "${0}-*"
+    return 0
 }
