[CS928-0531] 16 files changed, 408 insertions(+), 189 deletions(-).
Signed-off-by: Maxim Puchkov <maxim_puchkov@sfu.ca>

diff --git a/zsh/site-functions/error b/zsh/site-functions/error
--- a/zsh/site-functions/error
+++ b/zsh/site-functions/error
@@ -17,13 +17,65 @@
 #     and continue without returning any value.
 #       warning  'description...'
 #       error -0 'description...'
+#
 function error() {
-#    trap 'echo ${0}-*' EXIT
-#    echo "${0}-*"
+    #MARK: - Data
+    # Message
+    typeset message
+    typeset message_title
+    typeset message_desc
+    # Exit code
+    typeset exit_code=1
+    typeset exit_code_label
+    # Output
+    typeset output_device
     
-    # MARK: - Functions
-    # Capitalize first letter of the description
-    # and add a trailing period
+    
+    #MARK: - Functions
+    # Parse function options and flags
+    function error-parse-options() {
+        set -- $@
+        # Exit code flag (must be the first argument)
+        if [[ $1 =~ '-[0-9]+' ]]; then
+            exit_code=${1#-}
+            shift
+        fi
+        # Other options
+        while [[ $1 =~ '^-' ]]; do
+            case $1 in
+                # Display the exit code for errors
+                -c|--code)
+                    exit_code_label=" %F{7}[$exit_code]%f"
+                ;;
+                # Do not format description
+                -p|--plain-description)
+                    unfunction error-format-description
+                    function error-format-description() { return 0 }
+                ;;
+                # Silence output
+                -n|--null)
+                    output_device=/dev/null
+                ;;
+                # Stop parsing options
+                --) shift ;&
+                *)  break ;;
+            esac
+            shift
+        done
+        # Set description to the remaining arguments
+        message_desc="$@"
+        return 0
+    }
+    # Title - text, color, and exit code
+    function error-format-title() {
+        if [[ $exit_code -gt 0 ]]; then
+            message_title="%F{1}Error%f"
+        else
+            message_title="%F{3}Warning%f"
+        fi
+        return 0
+    }
+    # Description - capitalization, trailing period
     function error-format-description() {
         message_desc="${message_desc:-No description.}"
         message_desc="${(C)message_desc[1]}${${message_desc:1}}"
@@ -31,70 +83,32 @@ function error() {
            [[ ! "${(q)message_desc}" =~ '^.*\.$' ]]; then
             message_desc="${message_desc}."
         fi
+        return 0
     }
-    __XXX__PATTERN='[0=9]
-    # Parse function options
-    function error-parse-options() {
-        set -- $@
-        while [[ $1 =~ '^-' ]] &&
-              [[ $1 != '--' ]]; do
-            case $1 in
-                # Display the exit code for errors
-                -p|--print-code)
-                    exit_code_label=" %F{7}[$exit_code]%f"
-                ;;
-                # Do not format description
-                -n|--no-format)
-                    unfunction error-format-description
-                    function error-format-description() {
-                        return 0
-                    }
-                ;;
-                # Silence output
-                -0|--null)
-                    output_device=/dev/null
-                ;;
-                # Set the error return code
-                *)  if [[ $1 =~ '-[0-9]+' ]]; then
-                        exit_code=${1#-}
-                    else
-                        break
-                    fi
-                ;;
-                -<0-255>)
-                    
-                *)  break
-                ;;
-            esac
-            shift
-        done
+    # Message - title, description, and return status
+    function error-format-message() {
+        error-format-title
+        error-format-description
+        message="%U${message_title}%u${exit_code_label}"
+        if [[ -n $message_desc ]]; then
+            message="${message}: ${message_desc}"
+        else
+            message="${message}."
+        fi
+        return 0
+    }
+    # Format and print the error/warning message
+    function error-print() {
+        error-format-message
+        print -P -- "$message" >${output_device:-/dev/stderr}
+        return 0
     }
     
     
-    #MARK: - Data
-    # Exit code
-    typeset -i exit_code=1
-    typeset exit_code_label=''
-    # Output
-    typeset output_device=/dev/stderr
-    
-    error-parse-options
-    
-    # Title text
-    typeset message_title
-    if [[ $exit_code -gt 0 ]]; then
-        trap "return $exit_code" EXIT
-        message_title="%F{1}Error%f"
-    else
-        message_title="%F{3}Warning%f"
-    fi
-    # Description text
-    typeset message_desc="${(j:\n       :)@}"
-    error-format-description
-    
-    # Print the error/warning message to stderr
-    print -P -- "%U$message_title%u$exit_code_label: $message_desc" >&2
+    error-parse-options "$@"
+    error-print
     
     unfunction -m "${0}-*"
-    return 0
+    trap 'return $exit_code' EXIT
+    return $exit_code
 }
